### ISSUE TITLE
Cannot load images with colon in filename

### ISSUE THREAD

**Issue by moncasi** [lovell/sharp#1020]
Hello,
I have to resize a lot of files with special chars in their names. All is working but files with colon in their name like 4BhTRy5:1z.jpg
Here is the error message
Error: Input file is missing or of an unsupported image format

I used jimp before and there were no problems with colons in file   ##names.

Thanks

**Comment by lovell** [comment]
This is probably due to how the glib library, used by libvips to open files, handles relative paths. Your example `4BhTRy5:1z.jpg` is interpreted as `1z.jpg` with a protocol of `4BhTRy5`, neither of which exist.

Using absolute file paths everywhere solves most of these kind of problems and usually makes code more robust.

**Comment by moncasi** [comment]
Yes, you're right but I already use absolute paths like this : sharp(path.resolve(sourceFolder+'/'+filename))
I tried to replace all colons with a '\:' but it doesn't matter...
I'll be searching about glib and an eventual issue with colon in file names.

**Comment by moncasi** [comment]
I found this kind of bug reports. I tried with adding 'file://localhost' before the absolute path and that did not work too.
I did not try with relative paths.
I use the buffer from fs.readFile and that works well :)
Thanks

**Comment by lovell** [comment]
Thanks for the update. There's not a lot we can do here so I'm glad you found a workaround.
