### ISSUE TITLE
Expose vips_linear() transformation with sharp

### ISSUE THREAD

**Issue by 3epnm** [lovell/sharp#1022]
Hello,

I like the sharp project very much, but i miss the opportunity to do to a vips.linear() transformation. The more complex filter convolve instead is available. 

Is it possible to do a vips.linear() transformation with sharp and i missed this in the documentation, or can someone help me to extend this in sharp?

**Comment by lovell** [comment]
Hello, there's a (stalled?) PR at #742 - perhaps you could help with that?

**Comment by 3epnm** [comment]
Good hint - i guess this will help.

**Comment by lovell** [comment]
Landed in #1024, thank you, will be included in v0.19.1.

**Comment by lovell** [comment]
v0.19.1 now available, thanks for the PR.

**Comment by sebastienbarre** [comment]
Was this one always supposed to implement [vips-linear1](https://libvips.github.io/libvips/API/current/libvips-arithmetic.html#vips-linear1) instead of [vips-linear](https://libvips.github.io/libvips/API/current/libvips-arithmetic.html#vips-linear), the more powerful version using matrix/vector? Just asking because `recomb()` is supported by sharp, and uses a matrix as well...
