### ISSUE TITLE
Enhancing clarity of an image

### ISSUE THREAD

**Issue by zaidqureshi2** [lovell/sharp#1066]
Hey I have an image that I will be passing into tesseract, but before passing it in I need to enhance the "clarity" of the image for ocr. I can do this through windows photos "Edit=>Clarity" but want to know how I can get the same effect using sharp

Thanks

**Comment by lovell** [comment]
Hello, I may be wrong but I think this feature involves a technique called [Contrast Limited Adaptive Histogram Equalization](https://en.wikipedia.org/wiki/Adaptive_histogram_equalization#Contrast_Limited_AHE).

If so, libvips provides this via [hist_local](http://jcupitt.github.io/libvips/API/current/libvips-histogram.html#vips-hist-local) but this is not yet exposed in sharp.

The API could possibly look like something like the following:

```javascript
.clarity({ width: 5, height: 5, slope: 3.0 })
```
...where `width` and `height` must be odd integers (default requires experimentation, perhaps 5 or 7) and `slope` will typically be a float between 2.0 and 4.0 (default to 3.0).

**Comment by baparham** [comment]
I too, am looking for a sharp based CLAHE-like solution. I'm not c++ expert, so working on this myself is a bit confusing after trying to follow through the code path in the sharp source to expose this. Do you have any examples in the code of a similar function that is exposed that can be used as a model?

**Comment by dmitrizzle** [comment]
Also interested, also no C++ expert.

**Comment by baparham** [comment]
@lovell any advice?

**Comment by baparham** [comment]
I'll make an attempt at fixing this and report back here if I need additional help or get stuck.

**Comment by lovell** [comment]
v0.28.3 now available with this feature (thank you @baparham )

https://sharp.pixelplumbing.com/api-operation#clahe

**Comment by arthurwolf** [comment]
This is what I get applying clahe with width 3 height 3, rest default:

![panel-0-trimmed-contrast png-clahe](https://github.com/lovell/sharp/assets/108821/4b395c10-b3c2-4525-a1ae-680706a013a7)

What's going on?

**Comment by baparham** [comment]
Hi @arthurwolf can you clarify what are your expectations? Is there another industry tool that you are using for clahe that _is_ producing something you expect? To me it kind of looks like a normal result for a 3px window.

In my narrow use of clahe, really small local window sizes result in similar results to what you show. Have you experimented with larger window sizes or lower max slope?

If the results aren't what you are expecting, and you can back it up with examples from some other tool that offers clahe with similar settings, I'd recommend filing a separate bug. Making sure you can show that a direct call to libvips behaves differently would be critical too, since sharp just calls libvips local histogram equalization function almost verbatim.
