### ISSUE TITLE
include pngquant

### ISSUE THREAD

**Issue by littlestar1998** [lovell/sharp#1166]
good project!
But the ability to handle png images is too bad. Do you consider integrating pngquant?

**Comment by lovell** [comment]
Hello, the [pngquant](https://www.npmjs.com/package/pngquant) module probably provides what you're looking for.

**Comment by papandreou** [comment]
I believe it would be scope creep to integrate `pngquant` into sharp itself, maybe except for generating `PNG8`s when serializing an image that already has 256 or fewer colors.

That being said, I think there's space for a "meta" image processing engine that would build a pipeline out of other tools, including sharp and pngquant, so that a composite operation of eg. "rotate 90 degrees, resize to 400x300, then pngquant to 128 colors" would just work. I started woring on one a while ago (https://github.com/papandreou/impro) as an attempt to get rid of some extremely messy code in [express-processimage](https://github.com/papandreou/express-processimage). It's not quite usable yet, though, and maintaining it will probably require substantial effort. One of these days...
