### ISSUE TITLE
Strange behaviour with quality settings

### ISSUE THREAD

**Issue by bmaorlo** [lovell/sharp#1176]
Hi, 

I am trying to compress a PNG file and experience very strange behaviour. 

my original file is 2.4MB png image . when running it through Sharp with those settings 
var img = Sharp(data.Body)
                .jpeg({ quality: 75, force: false })
                .png({ compressionLevel: 8, force: false});

i am getting back 2Mb file size . 

When sending
var img = Sharp(data.Body)
                .jpeg({ quality: 75, force: false })
                .png({ compressionLevel: 5, force: false});

I am getting back 2.5MB 

While other online tools were able to reduce the file to 500kb. 

Anything to do here ?

Thanks !

**Comment by lovell** [comment]
Hello, please see #478, #600, #1017, #1110 and #1158, which all relate to the same question as to why a PNG file might be larger after processing.

**Comment by typedefstructer** [comment]
Hey, I looked at all the issues you have suggested, I cant find a answer on what to do so that the file will be smaller,  All theses links are pointing to other links and finally, there is something vague about libvips, All I want to know is that, is it even possible to fix it? If so please point me in the right direction, btw I am using this github.com/jimmynicol/image-resizer. @lovell

**Comment by lovell** [comment]
@typedefstructer http://sharp.pixelplumbing.com/en/stable/api-output/#png

> "PNG output is always full colour at 8 or 16 bits per pixel. Indexed PNG input at 1, 2 or 4 bits per pixel is converted to 8 bits per pixel."

**Comment by typedefstructer** [comment]
got it posterize options helped us, thank you @lovell

**Comment by aishwarya4shrestha** [comment]
posterize options? Can you please explain ?
