### ISSUE TITLE
Enhancement: Include channel bit depth in raw constructor options.

### ISSUE THREAD

**Issue by andrew-higgins-4d** [lovell/sharp#1289]
Sharp appears to store data internally with varying bit depths; i.e. it is possible to load a tiff file saved with 32 bits per channel and the resulting metadata shows a pixel depth format of 'float' instead of 'uchar'.

Currently, it doesn't seem to be possible to create a new sharp instance that will use anything other than 8 bits per channel. It would be useful to be able to set this via the constructor's 'options.raw' object. For example, setting 'options.raw.depth' to '32' or 'float' could then accept a Buffer containing a Float32Array.

The image data could then be saved to file without loss of precision for those formats that support it, or converted to the maximum supported bit depth before saving.

**Comment by lovell** [comment]
Hello, yes, it should be possible to add this feature. Is there a specific use case or integration you're thinking of that might help focus the initial approach? Happy to help with a PR if you're able.

**Comment by andrew-higgins-4d** [comment]
Hi, the use case is reading frame buffer data from a ray tracer which is stored as 32 bit floating point values per channel. The goal would be to maintain precision throughout, as the various render elements are often used during post processing later on.

I'm not sure if I'll have time to work on a PR at the moment, but I may be able to look into it at some point.

**Comment by lovell** [comment]
As discussed in #1315, the channel bit depth can be implicity determined from the type of the `TypedArray`. This means sharp would accept both `Buffer` and concrete `TypedArray` types for raw input.

**Comment by lu4** [comment]
Any progress on this issue? With little help on setting up the C++ debugging environment (standard approach through launch.json in Visual Studio Code wouldn't work) I think I would be able to come out with PR for this feature, anyone?

Thank you in advance!

**Comment by nnmrts** [comment]
I would also like to know the current state of this. Being able to use a Uint8Array or a Uint8ClampedArray would be a game-changer for me, and honestly, although it could be in the scope of this issue, I don't think it should be.

The input could just be "coerced" to the node.js Buffer by using Buffer.from. Or is that not a viable option?

**Comment by lovell** [comment]
@nnmrts 8 bit per channel raw data held in a `Uint8Array` should already "just work".

```javascript
sharp(Buffer.from(uint8Array), {
  raw: { width, height, channels }
})...
```
This future possible enhancement relates to other bit depths.

**Comment by nnmrts** [comment]
@lovell Thanks! I already do it like that in my codebase. What I'm saying is, #1315 was my "original" issue, but it redirected me to this issue, even though I don't think this issue is a dependency to the other one, #1315. I hope this comment isn't considered as off-topic, I just didn't want to necromance that other issue.

#1315's OP and my point was, it would be nice being able to write

```js
const uint8Array = Uint8Array.from([1,2,3,4]);

const resizedUint8Array = await sharp(uint8Array, {
  raw: { width: 32, height: 32, channels: 4 }
})
.resize(16)
.toUint8Array();
```

instead of

```js
const uint8Array = Uint8Array.from([1,2,3,4]);

const bufferOfThat = Buffer.from(uint8Array);

const resizedBuffer = await sharp(bufferOfThat, {
  raw: { width: 32, height: 32, channels: 4 }
})
.resize(16)
.toBuffer();

const resizedUint8Array = Uint8Array.from(resizedBuffer);
```

**before** we/you figure out how different bit depths should be handled. The "problem" is that
- input.js uses `is.buffer` https://github.com/lovell/sharp/blob/9431029917dcbb58f1a9302d7da090a5cf358973/lib/input.js#L31,
  - which uses `instanceof Buffer` https://github.com/lovell/sharp/blob/9431029917dcbb58f1a9302d7da090a5cf358973/lib/is.js#L48
- and input.js uses `Buffer.concat` https://github.com/lovell/sharp/blob/9431029917dcbb58f1a9302d7da090a5cf358973/lib/input.js#L187
  - [which is a node-specific static method](https://nodejs.org/api/buffer.html#buffer_class_method_buffer_concat_list_totallength) and isn't really required here, because it only gets one input, at which point it could just use `Buffer.from`, which is not node-specific, or even better, `Uint8Array.from`.

Either `is.buffer` (which would probably renamed then) should use `instance of Uint8Array`, which would work for node `Buffer`s too, because they are a subclass of Uint8Array.

Or the input should, as soon as we detect it's `instance of Uint8Array`, coerced to `Buffer` by using `Buffer.from`.

The input accepting `Uint8Array` would already be nice enough, but adding `toUint8Array` method as well would be perfect. That way, a user of sharp can choose by themself if they work with `Uint8Array`s or `Buffer`s. In my case, for my random project, I chose to solely use `Uint8Array` because it allows me to use `new Uint8Array()`, while `new Buffer()` is a security issue in node. Sure, `Buffer.from` works too, but in my opinion doesn't communicate well that you actually want to create a "new" `Buffer`. 
<hr>
What I wrote above about `Buffer.concat` can be ignored though, [as it accepts `Uint8Array`s as well anyways](https://nodejs.org/api/buffer.html#buffer_class_method_buffer_concat_list_totallength).

**Comment by lovell** [comment]
Happy to accept a PR to consider and accept `Uint8Array` as an "alias" of `Buffer` for input and/or output, if you're able.

**Comment by lovell** [comment]
v0.29.0 now available with this feature.
