### ISSUE TITLE
installation problem with v0.21.0

### ISSUE THREAD

**Issue by ChrisCindy** [lovell/sharp#1407]
When i try to install the new version(v0.21.0) of sharp in my server, i get the following error:
<img width="1241" alt="sharp-error" src="https://user-images.githubusercontent.com/10289782/46709605-0e6d0380-cc77-11e8-94b1-978d59179a01.png">
it seems that there is no file whose name is `sharp-v0.21.0-node-v59-linux-x64.tar.gz`.

the kernel version of my server is 
```
Linux version 3.10.0-514.16.1.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) )
```
and the operating system version is 
```
CentOS Linux release 7.2.1511 (Core)
```
 thanks a lot.

**Comment by lovell** [comment]
Hello, it looks like you're using Node version 9.11.1.

> "Pre-compiled binaries for sharp are provided for use with Node versions 6, 8 and 10 on 64-bit Windows, OS X and Linux platforms."

http://sharp.pixelplumbing.com/en/stable/install/

**Comment by Alan110** [comment]
i have the same problem.  in some network reason , i install sharp through the  SHARP_DIST_BASE_URL of my cdn. when i install sharp@0.21.0 , it was build faild . there was no exists the file vips/vip8.

libvips-8.7.0-linux-x64.tar.gz
![image](https://user-images.githubusercontent.com/7564425/46733732-b3adc900-ccc3-11e8-9583-f3e0e3f25a55.png)

but when i install sharp@0.20,  it was build success 

libvips-8.6.1-linux-x64.tar.gz 
![image](https://user-images.githubusercontent.com/7564425/46734048-ab09c280-ccc4-11e8-95f2-4f06a5d97ebb.png)


node version:  9.11.1
system info :  Linux version 3.10.0-514.16.1.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Wed Apr 12 15:04:24 UTC 2017

**Comment by lovell** [comment]
@Alan110 If the `SHARP_DIST_BASE_URL` environment variable is being intentionally set then you'll need to ensure whatever location it points at has the relevant files from https://github.com/lovell/sharp-libvips/releases/tag/v8.7.0

**Comment by danieldunderfelt** [comment]
Could the information about which Node versions have prebuilt binaries provided be added to the README? I don't depend in sharp directly and my installs were suddenly failing with an error message about an incompatible Node version (I'm on 11) which is normally solved by running `npm rebuild`. But on this occasion that doesn't work, so the easiest solution is to use Node 10 for this project with nvm. It would have been nice to have this information in the README instead of buried in the documentation site which I have no reason to visit if I don't use this package directly.
