### ISSUE TITLE
Png transparent + crop + fill 

### ISSUE THREAD

**Issue by maicolbruski** [lovell/sharp#1408]
Hi,

Im try generate a image png transparent with a crop + fill, but the image ignores fill and background:

```
sharp('./test.png')
    .resize(1280, 1280, {
        fill: 'red',
        fit: sharp.fit.contain,
        background: 'red'
    })
    .toFile('output.png', (err, info) => {
        console.log('ok');
    });
```
![output](https://user-images.githubusercontent.com/3951164/46756903-f27d5800-cc9e-11e8-90d5-688553d0a52d.png)

**Comment by lovell** [comment]
Hello, you're almost there. To `'contain'` the image on a fully-transparent background you'll need to specify a `background` that includes an `alpha` value of zero, e.g. `background: { r: 0, g: 0, b: 0, alpha: 0 }`.

(`'fill'` is a possible value of the `fit` property rather than a property in its own right so can be removed from your code sample.)

http://sharp.pixelplumbing.com/en/stable/api-resize/#resize

**Comment by maicolbruski** [comment]
Hi,

But using `background: { r: 0, g: 0, b: 0, alpha: 0 }` my background results all transparency.
I need a background color fill, its possible?

like this:

![component2](https://user-images.githubusercontent.com/3951164/46764610-42661a00-ccb3-11e8-893e-5854192c0a4b.png)

**Comment by lovell** [comment]
Did you see the [flatten](http://sharp.pixelplumbing.com/en/latest/api-operation/#flatten) operation?

**Comment by maicolbruski** [comment]
Hi Lovell,

Yes Tks!!!

Final code:

```
sharp('./test.png')
    .resize(1280, 1280, {
        fit: sharp.fit.contain,
        background: { r: 0, g: 0, b: 0, alpha: 0 }
    })
    .background('#ffffff')
    .flatten(true)
    .toFile('./output.png', (err, info) => {
        console.log('ok');
    });
```
