### ISSUE TITLE
Error: extract_area: bad extract area

### ISSUE THREAD

**Issue by davidgatti** [lovell/sharp#1444]
I know this error did pop up already in the issue section, but I decided to open a new one, because based on the threads it seams that what I do should work, but it doesn't. Let me explain:

I'm doing facial recognition, meaning I get the position and resolution where to find the face (bounding box). 

- The original image is: 1280x720
- The face is of size: 236x235
- And the position is: -0.03203125x0.15694444

I know, a minus value. I get that since AWS Rekognition returns the position in %, which I then convert in to the final position in pixels. From time to time I'll get a negative number - maybe because of a rounding number issue. Regardless – I did put an if statement to check if I get a negative number, and if I do, I replace the value to `0`.

```
{ left: 0, top: 0, width: 236, height: 235 }
```

Since we are so close to the edge, I don't need to be that precise. Never the less I get `Error: extract_area: bad extract area`. How can that be? What am I missing?

**Comment by lovell** [comment]
Hello, please can you provide a complete, standalone code sample and image that exhibits this behaviour.

**Comment by davidgatti** [comment]
Sorry but for now I won't have the time to debug this :(

**Comment by ackava** [comment]
@lovell This happens when extract box is outside of image.

Lets say image is `100,100` and when you say `extract( { left: 10, top: 10, width: 100, height: 100})`, it gives this error.

This can be resolved by either of following,
1. Throw an error saying extract box falls outside of image bounds
2. Trim extract box to image size, like in above example, width and height would become 90. So extracted image size would be 90x90.
3. Or extracted image size would be the same but it would contain blank parts where extract box falls outside. This would be ideal, mostly in case of png, outside part could be transparent.
