### ISSUE TITLE
Nearest neighbor upsampling stretching image

### ISSUE THREAD

**Issue by edwjusti** [lovell/sharp#1479]
Images are being stretched when resized with sharp.kernel.nearest, however the stretching only happens when the resolution is not an exact scale like 8 (1), 16 (2), or 24 (3). 

### Exact scale (x32) with kernel nearest:
![image](https://user-images.githubusercontent.com/17240777/49086945-e9d7e580-f23c-11e8-92c4-df7dc95fd17d.png)
### Non exact scale with kernel nearest:
![screenshot 172](https://user-images.githubusercontent.com/17240777/49087215-88fcdd00-f23d-11e8-8314-91f1a474195d.png)
### Non exact scale with default kernel:
![screenshot 171](https://user-images.githubusercontent.com/17240777/49087246-a467e800-f23d-11e8-9b11-b6e821bd06a7.png)

**Comment by lovell** [comment]
Hello, please can you share the input image and (standalone) code sample.

**Comment by edwjusti** [comment]
Here's the original image:
![image](https://user-images.githubusercontent.com/17240777/49117529-25e46800-f288-11e8-9896-59ed27ba2f4c.png)

And here's the code:
```javascript
const imageBuffer = /* ... */;
const size = 250; // causes stretching

const avatar = await sharp(imageBuffer).extract({
  left: 8,
  top: 8,
  width: 8,
  height: 8
}).resize({
  width: size,
  height: size,      
  kernel: sharp.kernel.nearest
}).png().toBuffer();
```

**Comment by jcupitt** [comment]
Hello, should be fixed in git master, thanks for the report! It was to do with the way centre vs. corner sampling is implemented.

With this 3x3 pixel PNG:

![3x3](https://user-images.githubusercontent.com/580843/49389524-76434600-f71e-11e8-9af5-8558d8c6b4bb.png)

If I run:

```
$ vips resize 3x3.png 3x3-nearest.png 83.33333333333 --kernel nearest 
$ vips resize 3x3.png 3x3-cubic.png 83.33333333333
```

I now see:

![3x3-nearest](https://user-images.githubusercontent.com/580843/49389594-9e32a980-f71e-11e8-98dc-301fd510945a.png)


![3x3-cubic](https://user-images.githubusercontent.com/580843/49389586-9541d800-f71e-11e8-9d71-c170d41b723a.png)

**Comment by lovell** [comment]
Thanks @jcupitt !

**Comment by lovell** [comment]
sharp v0.23.0 / libvips v8.8.1 is now available. Thanks for reporting this @edwjusti.
