### ISSUE TITLE
blurring a face in image(question)

### ISSUE THREAD

**Issue by jasan-s** [lovell/sharp#1518]
I am able to detect faces in an image and retrieve the rectangle that holds the discovered face relative to the detected image in the view coordinate system and the headEulerAngleY, headEulerAngleZ.
i.e `{"frame":[[94.8446044921875,56.383144378662109],[114.86393737792969,114.86395263671875]],"rotZ":2.3956208229064941,"rotY":-0.11730562895536423}`
Would it be possible to use this lib to blur the face given the bounding-box and the headEulerAngleY headEulerAngleZ?

**Comment by lovell** [comment]
Hello, to blur a rectangle within an image, you'd need to extract and blur, then overlay that output on top of the original image in a second pipeline, something like (untested):

```javascript
// top, left, width and height describe the rectangle containing the face

const blurredFace = await sharp(input)
  .extract({ top, left, width, height})
  .blur()
  .toBuffer();
const inputWithBlurredFace = await sharp(input)
  .overlayWith(blurredFace, { top, left })
  .toBuffer();
```

**Comment by lovell** [comment]
Hope this helped, feel free to reopen with more info if further help is required.

**Comment by siraisisatoru** [comment]
Hello, I have some questions related to your response above.

Basically, I am working on an image library for my blog.  I want to implement a blurry function for multiple rectangular sections of the image. Then I initially implemented a similar version as your responses but kind of different. The questions are:

1. I have a similar approach as yours but instead of using `overlayWith` but using `composite` functions. It seems working fine. So I want to ask is what is the difference between two functions?

2. When I tried to implement the blurry function, I assume that there will occur an extra 'double burr' if two sections were overlayed. To confirm, will I have such a 'double blur' on overlay sections? If so, is it possible to implement such a multi-blur without overlay section issues?

Your work is awesome and works fine for my project. I appreciate your work.
[This is my source code](https://github.com/siraisisatoru/hexo-sharp-script/blob/main/render/static.js) for your reference.
