### ISSUE TITLE
Raw input loses channel information on output

### ISSUE THREAD

**Issue by yamen** [lovell/sharp#1533]
Unsure if this is intended behaviour, but opening a raw buffer of grayscale (single-channel) images and then outputting a buffer changes it into three-channels. See below for quick proof:

```js
const sharp = require("sharp");

// simulate a 100x100 grid of black pixels, 10,000 bytes
let input = Buffer.alloc(100 * 100, 0);
console.log(`input: ${input.length}`);

// bring it into sharp with a single channel
let output = sharp(input, { raw: { width: 100, height: 100, channels: 1 } });

// expected 10000, get 30000
output.toBuffer().then(data => console.log(`output: ${data.length}`));

// expected 10000, now get 10000 by forcing a call to grayscale in the output pipeline
output.grayscale().toBuffer().then(data => console.log(`output via grayscale: ${data.length}`));
```

And actual output:

```console
input: 10000
output: 30000
output via grayscale: 10000
```

I was expecting that channel information would be retained during the pipeline, especially a pipeline with zero actions (in real life I'll be mostly cropping images).

(lovely work on the library btw!)

**Comment by lovell** [comment]
Hello, unless you tell it otherwise, sharp assumes the desired output is sRGB hence 3 channels.

As you've seen, using [greyscale](https://sharp.pixelplumbing.com/en/stable/api-colour/#greyscale) will downsample back to a single channel. You could also use [toColourspace](https://sharp.pixelplumbing.com/en/stable/api-colour/#tocolourspace) with a value of "b-w".

**Comment by lovell** [comment]
Hope this helped, please feel free to re-open with more details if not.
