### ISSUE TITLE
How to get base64 using sharp ?

### ISSUE THREAD

**Issue by sunnynegi** [lovell/sharp#1546]
Hi there i am using library for reducing image size before uploading to aws s3 bucket.
Here is my code please tell me how to get base 64 from sharp api.

`sharp(path).rotate().resize(300,300).toBuffer().then( async function(data) {
            console.log("i want base 64 ", data);
            try{
              const myApp = data.toString('base64');
              const mediaDoc = await createMediaObjects(myApp)
          })`

**Comment by papandreou** [comment]
sharp doesn't support base64 encoding the output image, but as you've found out it's easy to do that yourself outside of the library. Isn't that fine?

Previously asked here: https://github.com/lovell/sharp/issues/1337

**Comment by sunnynegi** [comment]
@papandreou  I checked but i got error { Error: Path must be a string without null bytes }

**Comment by papandreou** [comment]
@sunnynegi, hmm, it's hard to tell where that error is coming from without a stack trace. Also, I don't really understand what `createMediaObjects` is, or what you're actually trying to do.

I'm fairly sure this is not a problem with sharp, though.

**Comment by sunnynegi** [comment]
@papandreou Thanks, there is an problem in my code, well before closing this issue i want to ask one question. Is there any default api for sharp to get deafult image size, Well right now  my resize method is null.

`sharp(path).rotate().resize().toBuffer().then( function(data) {` 

Real image and sharp image have different height, width. How to set it default

**Comment by papandreou** [comment]
As far as I can tell, there's no concept of a default image size, `resize()` will preserve the width and height of the input image if you don't tell resize at least one target dimension. (I don't really understand what the use case for that might be?)

Since you're also passing `.rotate()`, what you're seeing might be that the width and the height are swapped because the image is being auto-rotated according to the EXIF `Orientation` tag, as described in http://sharp.pixelplumbing.com/en/stable/api-operation/#rotate

**Comment by lovell** [comment]
@sunnynegi Hope this helped, please feel free to re-open with more details if not.
