### ISSUE TITLE
Let me ask when I can use it on windows but when running on centOS, I can't and I report an error

### ISSUE THREAD

**Issue by tranquoctuyen97** [lovell/sharp#1559]
![image](https://user-images.githubusercontent.com/30342407/51822708-b59da580-230f-11e9-891f-0a470f86c23e.png)
please

**Comment by lovell** [comment]
Hello, this error suggests the input JPEG image is corrupt or invalid. If the problem persists, please provide a standalone code sample and test image that exhibits this behaviour.

**Comment by tranquoctuyen97** [comment]
This is my code
![image](https://user-images.githubusercontent.com/30342407/51876815-79645680-239c-11e9-905b-c818ce366fea.png)
end Experimental images
![image](https://user-images.githubusercontent.com/30342407/51876855-98fb7f00-239c-11e9-9bb0-689563128ede.png)

**Comment by lovell** [comment]
A screenshot of some code with unclear dependencies, rather than a standalone code sample that someone else can copy and paste, makes it hard for others to attempt to reproduce the problem and therefore being able to help.

Is the "Experimental images" a screenshot of Windows Explorer containing some images that cause problems or the problem image itself? If the former, again this approach will prevent others helping.

Having said that, from what I can tell, the input file path is based on incoming HTTP parameters so there is very likely to be a race condition where two incoming files both have the same filename and will overwrite each other. This is a problem in your code and not a problem in sharp - good luck!
