### ISSUE TITLE
Unable to use toColourspace('cmyk') with rotate()

### ISSUE THREAD

**Issue by brantleyenglish** [lovell/sharp#1567]
This code works properly:
```
    await sharp(imagePath).withMetadata().toColourspace('rgb-cmyk').rotate(-90).toBuffer().then( data => {
      fs.writeFileSync(imagePath, data)
  });
```
returns a RGBa colorspace image.

But this code returns a promise error:
```
    await sharp(imagePath).withMetadata().toColourspace('cmyk').rotate(-90).toBuffer().then( data => {
      fs.writeFileSync(imagePath, data)
  });
```
![](https://sh-drop.s3.us-east-1.amazonaws.com/be/Screen%20Shot%202019-02-05%20at%2010.41.34%20AM.png)

Is this colorspace 'toColourspace('cmyk')' invalid with rotate or buffer? Anything I could change to make this work?

Thanks! Any help is appreciated!

**Comment by lovell** [comment]
Hello, please subscribe to #1323 for updates to support for CMYK profile output.

The colourspace value `rgb-cmyk` isn't in the [supported list](https://github.com/libvips/libvips/blob/master/libvips/iofuncs/enumtypes.c#L713-L730) and I'd expect the first example to have failed at that point first - I'll check the validation is working correctly.

You should see the same problem if you remove the use of `rotate` so that operation is probably unrelated.
