### ISSUE TITLE
Can't install sharp

### ISSUE THREAD

**Issue by tutotau** [lovell/sharp#1582]
Hello!
Need help with install sharp on CentOS 6.

verbose stack Error: sharp@0.21.3 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
1165 verbose stack Exit status 1
1165 verbose stack at EventEmitter. (/root/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
1165 verbose stack at EventEmitter.emit (events.js:189:13)
1165 verbose stack at ChildProcess. (/root/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
1165 verbose stack at ChildProcess.emit (events.js:189:13)
1165 verbose stack at maybeClose (internal/child_process.js:970:16)
1165 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
1166 verbose pkgid sharp@0.21.3
1167 verbose cwd /var/www/brelishe/source
1168 verbose Linux 2.6.32-754.2.1.el6.x86_64
1169 verbose argv "/root/.nvm/versions/node/v10.15.1/bin/node" "/root/.nvm/versions/node/v10.15.1/bin/npm" "install" "sharp"
1170 verbose node v10.15.1
1171 verbose npm v6.4.1
1172 error code ELIFECYCLE
1173 error errno 1
1174 error sharp@0.21.3 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
1174 error Exit status 1
1175 error Failed at the sharp@0.21.3 install script.
1175 error This is probably not a problem with npm. There is likely additional logging output above.
1176 verbose exit [ 1, true ]

**Comment by lovell** [comment]
Hello, did you see https://sharp.pixelplumbing.com/en/stable/install/#linux

> For 32-bit Intel CPUs and older Linux-based operating systems such as Centos 6, compiling libvips from source is recommended.
> https://libvips.github.io/libvips/install.html#building-libvips-from-a-source-tarball

**Comment by r007** [comment]
I had almost the same problem on Ubuntu 18.04 LTS (32-bit system). It was throwing "undefined symbol" error similar to https://github.com/lovell/sharp/issues/649. Tried to install using yarn and npm, sometimes during build process I saw "glib-object no such file" error https://github.com/libvips/libvips/issues/1033

Here's what I've done:

1. Added most recent **disco** repository from Ubuntu 19.04.
```deb http://cz.archive.ubuntu.com/ubuntu disco main universe```
2. Run ```sudo apt-get update```.
3. Updated libvips from version 8.4.5 to 8.7.4 using the following command:
```sudo apt-get --only-upgrade install libvips```
4. Removed **node_modules** and re-installed all the packages using ```npm install```

Turns out that LTS repositories contain mostly outdated versions of the libraries. So you might want to update your CentOS installation from 6 -> 7. It should resolve your problem.
