### ISSUE TITLE
electron-builder and cross platform build

### ISSUE THREAD

**Issue by KillerCodeMonkey** [lovell/sharp#1697]
Hey there i want to build a macos electron app on an ubuntu machine.

Sharp is the only "native" module. But i think the problem is, that when electron-builder is running, it simply uses the linux native module instead of installing the version for the target electron build os.

Is this even possible or is there a way to achieve this?

The build on my CI works withou any error, but when i start my app it freezes directly without throwing an error. If i remove sharp, it works again.

I thought when this repo provides all native prebuilts electron-builder downloads the one necessary for the target platform.

**Comment by lovell** [comment]
The `prebuild-install` module used by `sharp` looks for the `--platform` flag when (re)building.

However https://github.com/electron/electron-rebuild/issues/176 suggests that `electron-rebuild` does not support this flag, which makes sense when compiling from source but not when using prebuilt binaries. Perhaps ask on that repo if they'll reconsider?

**Comment by KillerCodeMonkey** [comment]
Thanks for your fast response. I am a little bit confused which electron-userland build tools is using other libraries like electron-rebuild :D and how without digging to deep into them.

And in the electron-build documentation it is mentioned that crossplatform builds are possbile if the native module provides prebuilds for each platform.

`if your app has native dependency, it can be compiled only on the target platform unless prebuild is not used.

prebuild is a solution, but most node modules don’t provide prebuilt binaries.`

**Comment by KillerCodeMonkey** [comment]
Hey i checked the output of my ci when building the app on ubuntu for macos:

```
• rebuilding native production dependencies platform=darwin arch=x64
• rebuilding native dependency name=sharp
```

and electron-builder seems like to use node-pre-gyp

**Comment by lovell** [comment]
`sharp` provides pre-built binaries via `prebuild` rather than `node-pre-gyp`, but their approach is similar.

The options listed at https://www.electron.build/configuration/configuration#Configuration-buildDependenciesFromSource might help, e.g. `npmRebuild` might need to be set to `false` to prevent a compilation attempt.

Failing that you'll need to ask this on the relevant electron repo - good luck!

**Comment by KillerCodeMonkey** [comment]
@lovell yeah sorry to bother you with that. But like i said i lost my mind during searching through all the possibilities. And do not understand the arguments. I thought buildDependenciesFromSource does not use the prebuild ones, instead it builds the things from source code. and npmRebuild is the right option to rebuild node-modules for the correct platform during the build step.

So sorry and thanks for your help :). Nice support and fast.

**Comment by KillerCodeMonkey** [comment]
so i will close this issue here. Thanks again 👍

**Comment by ustun** [comment]
Sorry to bump a closed issue, but I think this is still the case and I think the only way to make it work is to build under the target platform rather than cross-compiling.

Here is what I found out:

1. Pre-v0.26, separate electron prebuilts were provided, but it seems that with v0.26, there is a single napi release.

electron-builder uses a package called `prebuild-install` internally, with the following command inside sharp directory:

`node ../prebuild-install/bin.js --platform=win32 --arch=x64 --target=8.5.2 --runtime=electron --verbose --force`

This fails since it makes a request to the following non-existent url: https://github.com/lovell/sharp/releases/download/v0.26.2/sharp-v0.26.2-electron-v76-win32-x64.tar.gz

pre-0.26, it was making a request to the following url, which succeeded:

**Comment by lovell** [comment]
@ustun As of v0.26.0, Electron should use the same N-API binaries as Node.js - see commit https://github.com/lovell/sharp/commit/dcc42f85148ba3697c6b56f803c485013c0ca29b - make sure you're not overriding `target` or `runtime` in your own configuration.

If you're still having problems, please open a new issue with a reference to a complete, standalone code repo that allows someone else to reproduce this.

**Comment by ustun** [comment]
Thank you for the explanation @lovell 

I believe the issue is with prebuilt-install and electron-builder. I'll ask those maintainers on how to proceed. 

In the meantime, we are planning to use GitHub Action to compile and get a prebuilt version for our needs.
