### ISSUE TITLE
Inherit from Transform instead of Duplex

### ISSUE THREAD

**Issue by greguz** [lovell/sharp#1704]
Looking inside the code, I noticed that the main `Sharp` class inherit from `Duplex` stream class. I'm not sure why this choice, but for me, it makes more sense to use the `Transform` class instead.

**Comment by lovell** [comment]
Hi, the use of Duplex is intentional as you may only want to stream data in _or_ out, whereas Transform is used when streaming data in _and_ out.

There are some examples in the tests for the various combinations of input and output method.

https://github.com/lovell/sharp/blob/05d76eeadfe54713606a615185b2da047923406b/test/unit/io.js#L64-L76

**Comment by greguz** [comment]
Got it, thanks.
