### ISSUE TITLE
Svg text on azure functions

### ISSUE THREAD

**Issue by eatfrog** [lovell/sharp#1722]
I'm building a small watermarking microservice on azure functions. I can't seem to get any svg text to render. I guess there is no fonts installed at all on the host os.

I have been trying to inline a font with base64, the svg works in the browser, but does not seem to use the font when running through sharp.

Example svg:
```html
<svg height="40" width="220" xmlns="http://www.w3.org/2000/svg" version="1.1">
        <defs>
            <style>
            @font-face {
                font-family: 'zzz';
                font-style: 'normal';
                src: url("data:application/font-woff;charset=utf-8;base64,d09GRgABAAAAAGbMABIAAAAAuWgAAQAA.....") format('woff');
              }            
              </style>
        </defs>
        <style><![CDATA[svg text{stroke:none}]]></style>
        <text x="20" y="30" font-size="35" fill="#fff" font-family="'zzz'" font-style="regular">test text</text>
</svg>
```

**Comment by lovell** [comment]
Please see https://gitlab.gnome.org/GNOME/librsvg/issues/153

**Comment by eatfrog** [comment]
any ideas as to how this could be accomplished through alternate means? doesnt have to be a specific font, just need to be able to actually output text.

**Comment by lovell** [comment]
Generic font families such as "serif" and "sans" might be OK.

librsvg uses fontconfig, which can be controlled via environment variables and config files - see https://www.freedesktop.org/software/fontconfig/fontconfig-user.html

**Comment by eatfrog** [comment]
neither serif nor sans worked. in the end, i could not get this to work.

I had to create a docker image and go that route instead. with docker, i could do a apt-get install fonts-roboto for example, and then the font would be in the system.

downside is, you can't use the consumption plan when using docker, instead you will have an app servie 24/7, so in the end it costs as much as hosting it as a regular website.

**Comment by lovell** [comment]
Perhaps you could ask at https://github.com/Azure/azure-functions-host about adding some basic fonts to the Azure Functions runtime environment.

**Comment by tonit-steve** [comment]
I had the same problem with Edge Lambda. Solution was to package the fonts with the Lambda and then set the envvar programmatically (because Edge Lambdas cannot have envvars) `process.env['FONTCONFIG_PATH'] = './fonts';`.

**Comment by vaibhavkaul69** [comment]
I faced an issue where text was being rendered as empty boxes on a template in my Node.js application hosted as an Azure Web App. Here's how I fixed it:

1. I discovered that Azure uses a Dockerized environment to host Node.js applications. The issue occurred because **fontconfig**, a Linux-based tool that manages font discovery and rendering, was missing from the configuration.

2. I used SSH to access my Azure Web App and installed **fontconfig**. However, it was installed globally, and all the data was erased after every deployment. This happened because Azure Web Apps do not persist data stored outside their main directory. In my case, the persistent directory was **/home**.

3. To solve this, I created a file named **install_fontconfig.sh** in the **/home** directory, ensuring the file would persist after each deployment.

4. I added the following commands to the script to install **fontconfig** and the required fonts:

```
apt-get update

echo "Installing apt-utils"
apt-get install -y apt-utils

echo "Installing required fonts..."
apt-get install -y fontconfig fonts-roboto

echo "Font installation completed!"
```

5. In the entry point file of my Node.js application (index.js), which I used with nodemon (nodemon index.js), I added the following code:

```
const setupScriptPath = path.join(__dirname, '../../install_fontconfig.sh');

if (isUndefinedNullOrEmpty(process.env['SCRIPT_EXECUTED'])) {
  exec(`bash ${setupScriptPath}`, (error, stdout, stderr) => {
    if (error) {
      commonAnalytics.logEvent('BASH_ERROR', {
        message: error.message,
        path: setupScriptPath,
      });
      return;
    }
    if (stderr) {
      commonAnalytics.logEvent('BASH_WARNING', {
        message: stderr,
        path: setupScriptPath,
      });
    }

    commonAnalytics.logEvent('BASH_SUCCESS', {
      path: setupScriptPath,
      output: stdout,
    });

    process.env['SCRIPT_EXECUTED'] = 'true';
  });
}
```


With this setup, the script executed once when the application started, installing **fontconfig** in the persistent **/home** directory. After this, **Sharp** was able to correctly detect the fonts from the system and render the text as expected.

I believe the only thing you need for the script to work correctly is **root permission**, which I believe you will already have so it should work fine.
