### ISSUE TITLE
Build failure in Netlify using Gatsby with imageSharp (segfault)

### ISSUE THREAD

**Issue by grantglidewell** [lovell/sharp#1788]
is this something that should be filed as an issue here? https://github.com/gatsbyjs/gatsby/issues/15611

**Comment by lovell** [comment]
As you probably saw, I helped investigate the linked https://github.com/gatsbyjs/gatsby/issues/6291 that turned out to be CircleCI over-reporting and over-comitting CPU (and possibly also RAM) on their build machines.

Are you using the latest version of Gatsby and setting GATSBY_CPU_COUNT=1 ? If so, my best guess would be that Netlify is as equally guilty here as CircleCI.

Good luck!
