### ISSUE TITLE
Intermittent GLib-CRITICAL crashes

### ISSUE THREAD

**Issue by tkazec** [lovell/sharp#180]
Hi, I'm looking into using sharp in production for my company's image renderer. I'm able to regularly reproduce a `(sharp:46231): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed` crash that kills everything.

Environment is a MacBook Pro w/ manual homebrew install and the latest Node 0.10.x. Code is literally just `sharp(path).toFormat(...).toBuffer(...)` running in `cluster` workers. Four workers run at once, each processing one image at a time. Running this at high load for less than a minute always causes this crash.

The scary part is it doesn't just crash the workers, it crashes the entire master process...

**Comment by lovell** [comment]
Hi Teddy, the `GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed` message is most likely to be a symptom rather than a cause. Kill any node process whilst one or more libvips' threads are still processing an image and you'll see it.

> "Four workers run at once, each processing one image at a time."

Each worker will process `process.env.UV_THREADPOOL_SIZE` (default=4) images at a time. Every image being processed spawns nCPU threads. https://github.com/lovell/sharp#sharpconcurrencythreads

What were the circumstances that led you to use the cluster module? Typically it's used to get around the single-threaded limitation of JavaScript running V8, spawning multiple single-threaded workers. sharp already contains multi-threaded behaviour via libuv and libvips, so you may see slightly worse performance and increased memory consumption with cluster.

If you're not already doing so, try logging which images you're processing to see if there's a pattern in behaviour just before a crash, e.g. the same image is always "in-flight".

Are you able to generate a backtrace at the point of failure via a tool such as `catchsegv`? (Could be tricky due to the use of child processes.)

Might you be using any sort of max-requests-per-child logic that could process.kill or process.exit a worker?

Does Node.js 0.12 improve the situation?

Are you allocating enough memory and file descriptors for the given task?

**Comment by lovell** [comment]
@tkazec have you been able to make any progress with this problem?

**Comment by tkazec** [comment]
@lovell Sorry for the delay - had to switch project focus to meet a deadline. This is on my todo and I'll get back to you within a couple weeks.

The reason I'm using cluster is because of PhantomJS (see https://github.com/buzzvil/ghost-town) and it's definitely possible it's running into one of the conditions you describe. I'll figure out exactly which one and let you know, and see if it's possible to just run sharp in the master process.

**Comment by lovell** [comment]
> "Might you be using any sort of max-requests-per-child logic that could process.kill or process.exit a worker?"

It looks like you are doing this here https://github.com/Buzzvil/ghost-town/blob/master/index.js#L199
```javascript
if (this._pageClicker >= this._workerDeath) {
    process.exit();
}
```
Your child processes could listen for this event and block the V8 thread until all their running libvips threads have joined/completed, perhaps something like:
```javascript
process.on('exit', function() {
  while (sharp.counters().process !== 0);
});
```

**Comment by lovell** [comment]
I'm pretty sure the use of `process.exit()` is causing this problem as it will kill any in-flight async tasks.

I'm closing this three-month old question but please do feel free to reopen if there are still problems.
