### ISSUE TITLE
TIFF support

### ISSUE THREAD

**Issue by smremde** [lovell/sharp#184]
When installing sharp with libvips-dev on ubuntu 14.04 it fails because I think the distro build does not contain TIFF support. If here any way sharp could detect the support of the library and only enable features that are supported? Would save me building vips fro source.

**Comment by lovell** [comment]
Hi Stephen, the forthcoming v0.10.0 of sharp uses run-time rather than compile-time format checks and should address this. Please can you try:
```sh
npm install lovell/sharp#judgement
```
It does however rely on libvips v7.40.0+ so this work-in-progress branch will probably also fail to compile against libvips [v7.38.5](http://packages.ubuntu.com/source/trusty/vips).

**Comment by lovell** [comment]
@smremde Were you able to try the `judgement` branch? Ubuntu 15.04 provides libvips [7.40.6](http://packages.ubuntu.com/vivid/libvips-dev) via package manager.

**Comment by lovell** [comment]
Closing this two-month old, non-updated question. Please feel free to reopen if there are still problems.
