### ISSUE TITLE
Input file contains unsupported image format on toFile call

### ISSUE THREAD

**Issue by devilcake** [lovell/sharp#1919]
Hello, I'm trying to make a function that will allow users to upload images to an online gallery, but want the images saved as .webps to save  on storage space. The images convert well but when trying to save them, no matter the parameters given to the toFile function, it returns the error in the title.

@Post()
    @UseBefore(authorizationMiddleware([RoleNames.CLIENT]))
    public async addToGallery(@CurrentUser() user: User, @UploadedFiles('files[]', { options: fileUploadOptions() }) files: any){
      let saved  
      if (files) {
            for (const file of files) {
              saved = await user.setGallery(file)
            }
          }
          const userWithGallery = await User.findOne(user.id, {relations: ['fileable', 'fileable.files']}) as User
          const filtered = userWithGallery.fileable.files.filter(file => file.type === 0  && file.hash.substring(file.hash.length - 5, file.hash.length) !== '.webp')
           for (const file of filtered) {
             let converted = sharp(saved)
             .webp({lossless: true})
             .toFile('output.tiff')//I've tried relative paths, getting the path by substringing the input file etc,
}
          return "Success"
    }

**Comment by devilcake** [comment]
Hi, thanks for the quick response. I've reformated the code a bit after consulting with the colleague who originally wrote it. The input file is of the type any, could that be the source of the problem?
@Post()
    @UseBefore(authorizationMiddleware([RoleNames.CLIENT]))
    public async addToGallery(@CurrentUser() user: User, @UploadedFiles('files[]', { options: fileUploadOptions() }) files: any){
      files.forEach(async pic => {
        console.log(pic)
        console.log(await sharp(pic.path).webp({lossless:true}))
      });

The result of the console.log(pic)
{ fieldname: 'files[]',
  originalname: 'sm_5aba147bcacf2.png',
  encoding: '7bit',
  mimetype: 'image/png',
  destination: 'C:\\Users\\SOMMAR~1\\AppData\\Local\\Temp',
  filename: 'abe51501368ae13c360b8c13ae510f56.png',
  path:
   'C:\\Users\\SOMMAR~1\\AppData\\Local\\Temp\\abe51501368ae13c360b8c13ae510f56.png',
  size: 75397 }

**Comment by lovell** [comment]
Does `C:\Users\SOMMAR1\AppData\Local\Temp\abe51501368ae13c360b8c13ae510f56.png` exist? Is it really a PNG image? Are you able to share it?

(As an aside, please see https://help.github.com/en/articles/creating-and-highlighting-code-blocks for some suggestions about how to format code in GitHub issues.)

**Comment by devilcake** [comment]
I'm sending a post request through Postman using a random png from google images. I've also tried using a jpeg. The code in my first post would store the image in a local folder then try to convert it. The conversion apparently goes through but fails when it's passed to any storage function (tried with toFile and toBuffer).

**Comment by mattpr** [comment]
I ran into this error today and so in the same error block I did an fs.stat on the input path I was feeding to sharp.

```
{"level":"error","timestamp":"2019-11-03T19:57:22.095Z","stack":"Error: Input file contains unsupported image format","message":"Input file contains unsupported image format"}
{"errno":-13,"code":"EACCES","syscall":"stat","path":"/var/www/upload/test.jpg","level":"error","timestamp":"2019-11-03T19:57:22.096Z","stack":"Error: EACCES: permission denied, stat '/var/www/upload/test.jpg'","message":"EACCES: permission denied, stat '/var/www/upload/test.jpg'"}
```
So in my case this is a permission error and doesn't have to do with the file format at all.  Would be awesome if sharp could differentiate permission errors from "I can read it, but don't like the contents".  Given permission errors are very common...I expect lots of people will run into this and go in circles due to the error message being about something other than perms.

```
# uname -a
Linux hostname-redacted 4.4.0-166-generic #195-Ubuntu SMP Tue Oct 1 09:35:25 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

node 10.16, sharp 0.23.2

**Comment by lovell** [comment]
@mattpr libvips currently only checks ENOENT - see https://github.com/libvips/libvips/blob/5df173dd15f5acc809690f0cfc427f4d077edbab/libvips/iofuncs/util.c#L1112 - so we'll need to modify libvips to also check other error codes and then add something to sharp to deal with this.

**Comment by lovell** [comment]
@mattpr I've created #1950 to track this.

**Comment by mattpr** [comment]
Thanks for the quick response and explanation about the underlying causes.  I also ran into something yesterday where `toFile` when used in callback mode is calling the callback before it has finished writing (or perhaps flushing) the file to disk.  Using `toFile` in promise mode doesn't seem to have this problem/behaviour.  I'm in the middle of some deadlines and didn't have a chance to dig very far or build any sample code...and perhaps this isn't a bug.  Just mentioning it while I am thinking about it since I haven't done enough research to warrant opening an issue.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further help is required.
