### ISSUE TITLE
tile() with background color

### ISSUE THREAD

**Issue by neave** [lovell/sharp#1923]
[libvips dszave](https://libvips.github.io/libvips/API/current/VipsForeignSave.html#vips-dzsave) provides a `background` option to set the default background color of the tiles, but this option does not seem to work in sharp. Am I doing this incorrectly or is this option not implemented?

Example:

	sharp('file.png')
		.tile({
			size: 512,
			overlap: 0,
			layout: 'google',
			background: '#000'
		})
		.toFile(tilesDirectory, (error, info) => {
			done();
		});

**Comment by lovell** [comment]
Hi, as you've seen, the `background` option of libvips' `dzsave` operation is not currently exposed in sharp.

https://sharp.pixelplumbing.com/en/stable/api-output/#tile

Happy to accept a PR to add this if you're able.

**Comment by neave** [comment]
OK thanks @lovell. I've had a go but C++ isn't my strong suit. See PR #1924.

**Comment by lovell** [comment]
v0.23.2 now available, thanks for the PR!

**Comment by michael7213** [comment]
hello paul i m with problems with star atlas

**Comment by michael7213** [comment]
> ```
https://staratlas.com/ 
![image](https://user-images.githubusercontent.com/57768203/69837947-03d14d00-1230-11ea-8095-1cce631d98e9.png) belt of venus and earth shadow 
the star atlas want the new atmosphere i want a new

**Comment by michael7213** [comment]
Precomputed Atmospheric Scattering Figure 7: Validation. The sky luminance relatively to the zenith luminance for several sun zenith and view zenith angles (and null azimuth between view and sun directions). Comparison between our model (with α¯ = 0.1, β
s
M = 2.210−5 m−1
, β
s
M/β
e
M = 0.9, g = 0.73 and HM = 1.2 km)
and the CIE sky model 12 (based on actual measurements). We note an overestimation near the horizon (view angles near 90 and -90), which
is also visible in Figure 6. As shown in [ZWP07] the Preetham model [PSS99] also suffers from this problem, which probably comes from the
physical models currently used in CG.
Figure 8: Results. (a), from top to bottom: [SFE07], single scattering, multiple scattering and photo. With [SFE07] the shadow does not
appear due to the missing ν parameter. It is too dark with single sattering only. (b) sunset viewed from space. (c) the view used for our
performance measurements.

c 2008 The Author(s)
Journal compilation
c 2008 The Eurographics Association and Blackwell Publishing Ltd.
E. Bruneton & F. Neyret / Precomputed Atmospheric Scattering
Figure 9: Results. Our results (no frames) compared with real photographs found on the Web (red frames). The tone mapping may explain
the sky hue differences on some images compared with the uncalibrated photographs.
Views from space for various altitudes and sun positions.
Views from the ground showing, from left to right, the Earth shadow, the aerial perspective after sunset, sunset, and light shafts at sunrise.
Aerial perspective during the day, and mountain shadows for various view and sun angles
