### ISSUE TITLE
Stream pipe with metadata

### ISSUE THREAD

**Issue by dreambit** [lovell/sharp#1995]
Hi.
Is it possible to rewrite this code with stream api? (without using buffers)

```
    const image = sharp(imageBuffer);
    const metadata = await image.metadata();

    return image
      .resize({
        width
      })
      .jpeg({
        quality: 87
      })
      .toBuffer({ resolveWithObject: true })
      .then(({ data: shot, info }) => processData(shot, info.width / metadata.width));
```
So here i need original image width and image width after transformation to calculate aspect ratio

Thanks.

**Comment by lovell** [comment]
Please see #236

**Comment by jasonkhanlar** [comment]
This is closed, however I think this code of mine is related:

`let image_input = sharp('./assets/pokemon/collection/Z.png');
let metadata_before_resize = await image_input.metadata();
image_input = sharp(await image_input.resize({ width: 100 }).toBuffer());
let metadata_after_resize = await image_input.metadata();`

Particularly it seems that I have to create a new sharp image in order to detect new dimensions, since the data returned after resize, and also after toBuffer, it does not seem possible to detect new metadata dimensions without first reparsing through another instance creation of the image using sharp function/method

**Comment by jasonkhanlar** [comment]
This is closed, however I think this code of mine is related:

```
let image_input = sharp('./Z.png');
let metadata_before_resize = await image_input.metadata();
image_input = sharp(await image_input.resize({ width: 100 }).toBuffer());
let metadata_after_resize = await image_input.metadata();
```

Particularly it seems that I have to create a new sharp image in order to detect new dimensions, since the data returned after resize, and also after toBuffer, it does not seem possible to detect new metadata dimensions without first reparsing through another instance creation of the image using sharp function/method
