### ISSUE TITLE
.svs file issue

### ISSUE THREAD

**Issue by h26liu** [lovell/sharp#2192]
Hello there,

I am trying to convert a .svs (whole slide image) to .dz (deep zooming) image. (on Windows10)

An error catched saying, "source input: Compression scheme 33005 tile decoding is not implemented"

Here is my code:
`sharp('input.svs')
    .png()
    .tile({
        size: 512
    })
    .toFile('output.dz')
    .then(data => { console.log(data) })
    .catch(err => { console.log(err) });`

Thank you for your help in advance!

**Comment by lovell** [comment]
The prebuilt binaries provided by sharp do not include openslide.

 See #1589 for a possible workaround.

On Windows, you'll need the vips-dev-w64-all-* files from https://github.com/libvips/libvips/releases

**Comment by h26liu** [comment]
Thank you for your quick response!

It seems like globally installed libvips won't be recognized when I do npm install sharp.. Any advice? 

Thanks again..

**Comment by lovell** [comment]
> "The use of a globally-installed libvips is unsupported on Windows."
> https://sharp.pixelplumbing.com/install#custom-libvips

Perhaps try using vips at the command line.

**Comment by h26liu** [comment]
Thanks for your help.. It finally got configure correctly..

**Comment by twilson7755** [comment]
I am trying to do something very similar ... utilize an openslide enabled version of sharp running in a ubuntu container.  I was able to successfully follow the work around described in #1589 to get my node application running on windows, however, it is not entirely clear to me how I should be doing this on Linux.  I grabbed a docker container from the vips github in order to build the openslide version of it but not sure what the next step is?  I have a ubuntu container with node and sharp installed but it is not clear to me how I should be installing a 'global' version of vips and make sharp aware of it as described in https://sharp.pixelplumbing.com/install#custom-libvips.  Any help you can provide would be greatly appreciated!

**Comment by twilson7755** [comment]
My issues have been resolved based on the following:
https://github.com/libvips/libvips/issues/1668
