### ISSUE TITLE
Using nohalo/lohalo for downscaling

### ISSUE THREAD

**Issue by Xaekai** [lovell/sharp#2193]
What are you trying to achieve?
NoHalo downscaler kernel

Hello. Searching issues leads me to believe this used to be supported, but I can't find the exact moment it was dropped or the rationale for it?

**Comment by lovell** [comment]
HI, "nohalo" is considered an interpolator rather than a kernel in libvips. The `vips_resize` function internally switched from using `vips_affine` and interpolators to `vips_reduce` and kernels from libvips v8.3.0 (Jan 2016) onwards.

Custom interpolators such as "nohalo" are still available via `vips_affine`, but this is not exposed in sharp - see #2095 for the future possible enhancement to do so.

**Comment by Xaekai** [comment]
Thank you. I believe that closes this issue, since the question is "what happened to nohalo."
Have a great day.
