### ISSUE TITLE
Conveting svg to png takes very long

### ISSUE THREAD

**Issue by talbenmoshe** [lovell/sharp#2424]
Hi,
There are SVGs that take very long to convert to PNG using Sharp.
In this [example](https://github.com/talbenmoshe/sharp-svg-to-png) is takes about 21 seconds.

I know it's a longshot - but is there anything that can be done to speed it up?

Today I use Puppeteer on the server that uses canvas to render the PNGs. It takes about 7 seconds to render about 40 svgs in parallel 😃  - But I really want to replace puppeteer (it has it's own issues...)

**Comment by lovell** [comment]
The underlying librsvg library takes about 11 seconds to render this SVG:
```sh
$ time rsvg-convert test.svg -o out.png

real	0m10.725s
user	0m27.048s
sys	0m2.335s
```

Did you see the `compressionLevel` option of `png()`? Perhaps try a lower value than the default of 9 to speed up the PNG compression part of this scenario. 

https://sharp.pixelplumbing.com/api-output#png

**Comment by talbenmoshe** [comment]
Thanks for the suggestion!
I just tried all `compressionLevel`s from 0-9. Unfortunately it makes no difference

**Comment by lovell** [comment]
To cap memory usage, libvips renders SVG images via librsvg in 2000px high partial strips.

This test case is 7500px high, so will result in four calls to librsvg to render the whole image. The SVG contains five 5000px Gaussian blurs, which will probably be the slowest part, and due to their size will span multiple strips so pretty much the whole SVG has to be rasterised each of those four times.

If you're able to reduce the size of the blur then if should be possible to make this sample input SVG faster in both librsvg and Chrome.

**Comment by talbenmoshe** [comment]
Took me a while to make the modifications, but your comment was very helpful!
I found out that I can reduce the size of the filters to exactly mathc the size of the relevant elements (which are much much smaller than 5000px)
By doing so it reduced the time to about 2-3 seconds!!!

Seems like it's bye bye puppeteer after all 😄 
Thanks a lot for the help!
