### ISSUE TITLE
Prebuilt binaries for Electron (0.26+)

### ISSUE THREAD

**Issue by adriendurepaire** [lovell/sharp#2440]
Thanks for your awesome work on sharp. It sounds like there isn't electron prebuilt binaries since the release of 0.26. 
The latest prebuilt binary was on https://github.com/lovell/sharp/releases/tag/v0.25.4. 

Is it intentional or is it an issue with CI?

**Comment by lovell** [comment]
Hi, separate prebuilds are no longer required for Electron as all binaries support N-API version 3.

https://nodejs.org/api/n-api.html#n_api_n_api_version_matrix

**Comment by mceachen** [comment]
@lovell thanks, as always, for your work on sharp!

I've had to pin to Electron v9.3 and sharp v0.23.4 to support Ubuntu 18.04.5 LTS. 

(In other words, prior code and config *does* work, but electron v10 + sharp v0.26 + ubuntu 18.04 fails due to #2058).

1) Is this error surprising, or expected? (I know that Electron is a huge dog's breakfast of problems, and I pre-apologize).

2) If it's expected, do you have any links I can follow or clues I can pursue to get the latest sharp to work with electron across macOS, Windows 10, and Ubuntu? (We talked earlier about building Electron with statically-linked dependencies, but that doesn't seem to be a supported build config).  

If there's a known-working happy path per OS, I'm happy to do whatever it takes to make each platform work individually. 

Thanks again. I'd be happy to write up whatever turns out to be the magick recipes into a docs pull request.

**Comment by lovell** [comment]
@mceachen I think the problem you're facing is because Electron depends on Chromium, which on Linux depends on GTK that depends on libcairo.

The prebuilt binaries currently provided by Electron for Linux depend on the system GTK and therefore the system libcairo.

There's some discussion about migrating Chromium in Electron from GTK to Aura at https://github.com/electron/electron/issues/10915

**Comment by adriendurepaire** [comment]
> Hi, separate prebuilds are no longer required for Electron as all binaries support N-API version 3.
> 
> https://nodejs.org/api/n-api.html#n_api_n_api_version_matrix

Hi, thanks for your answer. I think my issue is related to https://github.com/lovell/sharp/issues/1697#issuecomment-713574746. electron-builder tries to find prebuilt binaries and fails. So that's not an issue with sharp.

![image](https://user-images.githubusercontent.com/33576999/99306218-2ac7cb00-2855-11eb-9911-5516cd9a101a.png)

**Comment by lovell** [comment]
My best guess would be that `electron-builder` needs to be modified, either to skip dependencies that uses N-API, or to invoke `prebuild-install` with `runtime=napi` first, then fallback to `runtime=electron`.

**Comment by lovell** [comment]
Downstream issue for this at https://github.com/electron-userland/electron-builder/issues/5438
