### ISSUE TITLE
error: 'darwin-x64' binaries cannot be used on the 'linux-x64' platform.

### ISSUE THREAD

**Issue by roycemento** [lovell/sharp#2443]
I am created an image based on my app and when i am trying to run a container based on that image I getting an error connect to sharp.

Dockerfile: 

FROM node:10.20.1

WORKDIR /app

COPY package.json .

RUN npm install -g node-gyp

RUN npm install

EXPOSE 8080

CMD [ "npm", "start" ]

The error i am getting is: 

/app/node_modules/sharp/lib/libvips.js:68
      throw new Error(`'${vendorPlatformId}' binaries cannot be used on the '${currentPlatformId}' platform.
 Please remove the 'node_modules/sharp' directory and run 'npm install' on the '${currentPlatformId}' platform.`);
   
Error: 'darwin-x64' binaries cannot be used on the 'linux-x64' platform. Please remove the 'node_modules/sharp' directory and run 'npm install' on the 'linux-x64' platform.

**Comment by lovell** [comment]
https://sharp.pixelplumbing.com/install#common-problems

> The architecture and platform of Node.js used for `npm install` must be the same as the architecture and platform of Node.js used at runtime.

**Comment by roystern92** [comment]
HI thank for your replay.
I still didn't figure out how to fix it and make my container run.
Can you explain in more detail?

**Comment by lovell** [comment]
> Error: 'darwin-x64' binaries cannot be used on the 'linux-x64' platform.

> The architecture and platform of Node.js used for npm install must be the same as the architecture and platform of Node.js used at runtime.

The error message suggests `node_modules` was populated by running `npm install` on macOS/Darwin, which won't work on Linux. Make sure you're not sharing or copying an external `node_modules` within the Linux container.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.

**Comment by kohtala** [comment]
Hi. I found this error appears on about 20 issues. I just comment now on this recent issue rather than create yet another.

Sharp currently looks if the platform in `vendor/${minimumLibvipsVersion}/platform.json` file matches the currentPlatformId. For example [node-sass](https://github.com/sass/node-sass) does a little differently and uses instead the platform in the directory name `vendor/${process.platform}-${process.arch}-${process.versions.modules}`. That allows download of binaries for many platforms in same worktree. They also have an [install.js](https://github.com/sass/node-sass/blob/master/scripts/install.js) script that by default downloads the binary for current platform, but takes options for other platforms.

Perhaps something like that would work for sharp as well?

As background, I have a worktree where I can code and need the dependencies for vscode intellisense and unit tests. But for integration tests and debugging, it needs to communicate with other services and docker-compose sets that environment up. I just map the worktree to the container as a volume and it can restart with nodemon on source code changes. It also listens for debugger. But the node image is the alpine image with different platform from host.

Alpine, btw., would have precompiled libvips.so binaries that seem new enough. But it does not ship with the pkg-config files sharp seems to be wanting. Would be nice if it would be possible to change the install to use the binary from alpine distribution while making other changes. It would help avoid external downloads. We would prefer limiting who we trust and verify all download sha256 hashes we can during build to know what we have in the image.

**Comment by vimalmistry** [comment]
Same issue. I am using Mac Bigsur

```
web_1    | /usr/src/app/node_modules/sharp/lib/libvips.js:82
web_1    |       throw new Error(`'${vendorPlatformId}' binaries cannot be used on the '${currentPlatformId}' platform. Please remove the 'node_modules/sharp' directory and run 'npm install' on the '${currentPlatformId}' platform.`);
web_1    |             ^
web_1    | 
web_1    | Error: 'darwin-x64' binaries cannot be used on the 'linux-x64' platform. Please remove the 'node_modules/sharp' directory and run 'npm install' on the 'linux-x64' platform.
```

My Dockerfile

```
FROM node:16

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json ./
# COPY package-json.lock ./
# COPY yarn.lock ./



# RUN yarn install
RUN rm -rf node_modules build
RUN npm i
RUN npm i --platform=linux sharp
# Copy in the source
COPY . .


RUN npm run build

# Expose Port
EXPOSE 9001

# Run the app
CMD ["node", "build/index.js"]
```
