### ISSUE TITLE
If we want to enable handling of large images like 100mb then what should be the way?

### ISSUE THREAD

**Issue by ksoni301** [lovell/sharp#2683]
I want to convert 100mb large image to different sizes. I've created azure function to convert the images. But currently it's only handling 30mb image but I want to add the support to handle 100mb large image.

**Comment by dmitrizzle** [comment]
I regularly handle 200mb+ images; I don't think I've even got the streaming set up properly yet. I'm using Node 14 running on Alpine on a weak Heroku container (500mb memory) which seems to work OK-ish and should improve once I ensure I stream the data instead of stuffing the whole thing down at once. This is for processing one file at a time though, so depending on your setup you may need to set up queueing server and perhaps a way to spin up on-demand instances if you get a lot of requests.

**Comment by lovell** [comment]
The general advice for function-as-a-service platforms is to set the memory level as high as possible as this also usually provides the highest slice of CPU time too.

The Azure "consumption plan" offers up to 1.5GB and "premium plan" goes up to 14GB, which should be more than enough.

https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale#service-limits

**Comment by ksoni301** [comment]
I changed my plan to premium, now it's showing me error "Input image exceeds pixel limit" for 100mb image. What can cause this error?

**Comment by lovell** [comment]
Did you see the `limitInputPixels` option? Use this only for trusted input.
```js
sharp(input, { limitInputPixels: false })...
```
https://sharp.pixelplumbing.com/api-constructor

**Comment by ksoni301** [comment]
Thank you for your quick response @lovell. I tried the limitInputPixels ad sequentialRead in the constructor and it worked well with consumption plan also. No need to shift to premium plan for now as it's processing 100mb image smoothly.
