### ISSUE TITLE
svg direction rtl not supported

### ISSUE THREAD

**Issue by baravak** [lovell/sharp#2722]
svg:
![image](https://user-images.githubusercontent.com/953471/118523079-08563200-b752-11eb-9154-fc4b6b106c91.png)

png:
![image](https://user-images.githubusercontent.com/953471/118523034-fb394300-b751-11eb-9406-2b44672f63b2.png)

**Comment by lovell** [comment]
Please can you provide the SVG file.

**Comment by lovell** [comment]
I tried with a Farsi example taken from https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/direction
```svg
<svg viewBox="0 0 600 72" xmlns="http://www.w3.org/2000/svg"
    direction="rtl" lang="fa">
  <text x="300" y="50" text-anchor="middle"
      font-size="36">داستان SVG 1.1 SE طولا ني است.</text>
</svg>
```
Here's the PNG output from the latest version of sharp, which I think is as-expected:

![](https://user-images.githubusercontent.com/210965/118974576-e683c780-b96a-11eb-9205-4f80da70fdb3.png)

Could this be an alignment rather than direction problem?

**Comment by lovell** [comment]
There's another example of this problem in #2885 - looks like we'll need to fix this upstream in librsvg.
