### ISSUE TITLE
Better documentation for metadata support

### ISSUE THREAD

**Issue by yankeeinlondon** [lovell/sharp#2760]
This library is fantastic and it clearly hints at some support for XMP, IPTC, and EXIF but the documentation is very light and it makes it hard to understand how one would get to the data and/or write it back out to converted files.

I read this [old thread](https://github.com/lovell/sharp/issues/650) on EXIF and found it very informative but I still remain  unclear on how to proceed. I would really love to see a bit more in the docs and/or in some example files.

Of course, being a bit of a TS junkie, I am in many ways a fan of allowing the types to be the documentation for details. And this is probably an area where a lot more could be done. 

For instance, `WriteableMetadata` shows **exif** as a property with the following opaque definition:

```ts
Record<string, any>;
```

Now I suspect, but don't know, that formal typings for the EXIF spec in Typescript do not exist (at least my google skills appear not to have found it) but one could easily help users considerably even with a subset like so where they _get_ the most commonly used fields strongly typed but can add any others which they want to use themselves:

```ts
export type ExifMetadata<T extends object = {}> = {
  Copyright?: string;
  Orientation?: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;
  Make: string;
  Model: string;
  ImageDescription: string;
  Software: string;

  ModifyDate: DateTimeDigitized;
  OffsetTime: string;
  CreateDate: DateTimeDigitized;
  OffsetTimeDigitized: DateTimeDigitized;

  Rating: number;
  RatingPercent: number;

  SubjectDistance: number;
  BrightnessValue: number;
  ExposureCompensation: ApexValue;
  ShutterSpeedValue: ApexValue;
} & T;
```

> Note: this was just a quick stab at "representative fields" and I used [link](https://exiftool.org/TagNames/EXIF.html) as reference

Also by looking at this typing file I am _inferring_ (a dangerous thing) that only EXIF data can be written to a file but I believe the docs suggest that support for IPTC and XMP exists to some degree but this is fully missing here.

**Comment by lovell** [comment]
Hi, the TypeScript definitions for sharp are maintained by the DefinitelyTyped repo:
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/sharp

Perhaps you could open a PR there to add these fields to`WriteableMetadata`. If you are able to do this, this object should probably include an "indexer" that allows any other properties:

```typescript
interface WriteableMetadataExif {
  IFD0: {
    Copyright?: string;
    ...
    [x: string]: any;
  },
  IFD1: {
    ExposureTime?: number;
    ...
  }
}
```
You could use the following as a partial source of property names too:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/exif/index.d.ts

> I believe the docs suggest that support for IPTC and XMP exists to some degree but this is fully missing here.

Neither can be updated, but if the input image has them they are passed through.

**Comment by ksnyde** [comment]
I've never actually done a PR for **DefinitelyTyped** before. I presume the PR is sent to the master repo but how does it get reviewed and approved? Is there a central authority or is it farmed out to individuals? Either way, I'll give this a go and get it started.

**Comment by ksnyde** [comment]
<img width="522" alt="image" src="https://user-images.githubusercontent.com/980757/122657047-c6cff280-d114-11eb-92fe-2fc6966e5461.png">

@lovell do you happen to know the distinction between IFD0 and ExifIFD? More specifically, would Sharp be able to handle **ExifIFD**?

**Comment by ksnyde** [comment]
I'm almost done with a first pass, but at a high level the `WriteableMeta` would look like this:

```ts
interface WriteableMetadata<T0 extends object = {}, T1 extends object = {}> {
    /** Value between 1 and 8, used to update the EXIF Orientation tag. */
    orientation?: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;
    /** Filesystem path to output ICC profile, defaults to sRGB. */
    icc?: string;
    /** Object keyed by IFD0, IFD1 etc. of key/value string pairs to write as EXIF data. (optional, default {}) */
    exif?: {
        IFD0: ExifIFD0<T0> & Record<string, any>;
        IFD1: T1 & Record<string, any>;
        [key: string]: any;
    };
    /** Number of pixels per inch (DPI) */
    density?: number;
}
```

This provides really good strong typing for popular IFD0 tags as well as:

1. the ability to pass in a generic  `<T0>` to _extend_ strong typing
2. any _additional_ key/value pair is still allowed (obviously without strong types)

I personally have very little to no need for IFD1 -- as I suspect is the case for many -- so I've left it as a generic structure but I have included a generic `<T1>` which can be used to provide strong typing on that too if someone desires. 

In order to expose the generics in a way that people can use them, I have added these to the `withMetadata` function:

```ts
withMetadata<T0 extends object = {}, T1 extends object = {}>(withMetadata?: WriteableMetadata<T0, T1>): Sharp;
```

**Comment by ksnyde** [comment]
Keen on hearing back from you on the **ExifIFD** question from above as that'd give me an opportunity to add some more useful tags. Outside of that I can push the PR.

**Comment by ksnyde** [comment]
Also, one other question ... how do I get the `exif`, `iptc`, `xmp` and `tifftagPhotoshop` buffers into key/value pairs. I tried just converting the buffer to a string but that ended in tears.

**Comment by ksnyde** [comment]
Since we're operating in different timezones -- I suspect based on the UK spellings prevalent in this repo (I'm in LA though lived most of the last 20 years in London) -- I've created a type `ExifIFD<T>` in the PR. It's not currently used anywhere yet but can be added easily if it's **Sharp** can handle them.

**Comment by ksnyde** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53942

**Comment by lovell** [comment]
> do you happen to know the distinction between IFD0 and ExifIFD? More specifically, would Sharp be able to handle ExifIFD?

I think the ExifIFD (sub)directory is usually IFD2, at least in JPEG images.

> how do I get the exif, iptc, xmp and tifftagPhotoshop buffers into key/value pairs.

If this question refers to reading `metadata()` of an input rather than setting `withMetadata()` of an output, then these are `Buffer` instances, as documented.

https://sharp.pixelplumbing.com/api-input#metadata

You'll need to use other modules to parse these e.g. https://www.npmjs.com/package/iptc-reader

**Comment by ksnyde** [comment]
Gosh, just when I thought I'd figured it out. How does the term "subdirectory" apply here?

**Comment by lovell** [comment]
We're quite deep into EXIF spec territory here, but my understanding is that IFD0 can optionally contain an offset to subdirectories, and if so one of these is ExifIFD, which will be presented as IFD2.

**Comment by ksnyde** [comment]
The other tools i'm using to understand the EXIF name/value pairs do not distinguish between these blocks at all. Is there any effort underway to pull out the metadata as key/value pairs on the read side? I thought I remembered that being discussed in another issue? If it were, would these blocks (aka., IFD0, IFD2, etc.) be visible as top level keys?

**Comment by lovell** [comment]
Were you able to make any progress with this? If not, is there a sample image that we can use as a concrete example to help work out what metadata might be missing?

**Comment by ksnyde** [comment]
Sorry I've been focused elsewhere. I'm a classic ADHD sufferer ;)

**Comment by ksnyde** [comment]
In terms of metadata missing ... I feel where I kind of gave up is I don't fully understand how to get at existing EXIF and IPTC data which are stored in Buffer format. It felt like this was more of a secondary concern for Sharp (where the focus was more on the conversion of actual pixels, etc.). 

Based on the high praise that ExifTools gets from developers and photographers but maybe more concisely it's abstraction away from having to deal with IFD_x_ concerns, it may be worth seeing this as a dividing line in terms of separation of concerns? 

I mean, by all means I greatly prefer a C-based (wrapped in npm) entry point like Sharp but a lot of batch image conversion is done via a CLI where good 'ol Perl is an ok answer (although it has literally been decades since I touched Perl).

**Comment by ksnyde** [comment]
Note: **ExifTool** does seem to have a high quality wrapper in **npm**: https://photostructure.github.io/exiftool-vendored.js/

**Comment by loverdeveloper** [comment]
Hi, I'm a little bit confused here, i don't know how to set DateTimeOriginal, ModifyDate, CreateDate for ex

**Comment by lovell** [comment]
@loverdeveloper Please can you add this information to the question you've already opened at https://github.com/lovell/sharp/issues/3027

**Comment by lovell** [comment]
Closing as https://www.npmjs.com/package/exiftool-vendored is probably the right tool for the job when more extensive EXIF metadata editing is required.
