### ISSUE TITLE
Using `look`-branch in AWS-Lambda-Function

### ISSUE THREAD

**Issue by emmanuelmillionaer** [lovell/sharp#292]
In order to be able to run sharp in an AWS-Lambda-Function:
I'm using the branch `look`:

       npm install lovell/sharp#look

Now my problem is that the function zip file increased 
from 19.4 MB to 84.2 MB

Uncompressed, `node_modules/sharp` has a size of <b>168.2 MB</b>

<b>How can I decrease the size? Which files can be deleted?</b>
In my case I initialize sharp with an jpg image buffer and resize it

<b>Thanks for your help</b>

**Comment by lovell** [comment]
Installing from a git branch rather than via the npm registry means you'll get all the test fixtures, so you can remove the `node_modules/sharp/test` directory for instant savings.

If `npm install` won't be run again you should be able to remove `node_modules/sharp/include`.

You *might* be able to get away with removing some of the shared library files that end up in `node_modules/sharp/lib` if you don't require them, e.g. libtiff, but this *could* cause random segfaults at runtime.

Finally, if you're not already using the LZMA or Zopfli algorithms, perhaps try those to see if whatever AWS uses to unpack the .zip files supports them, i.e. treat the .zip as a container rather than a codec.

Please remember that the `look` branch is a work-in-progress and may break so please don't rely on this for production purposes. Please subscribe to #42 for updates. Good luck!

**Comment by emmanuelmillionaer** [comment]
@lovell  Thanks for your help and for the development of sharp!

I followed your steps however my package is still to big. 
Now the package size its at 51 MB, 50 MB would be ok
http://docs.aws.amazon.com/de_de/lambda/latest/dg/limits.html

Im really looking forward to be able to use it on Lambda! 
I will Keep an Eye on this repository! :+1:  :smiley:

**Comment by lovell** [comment]
@emmanuelmillionaer Please can you try the `look` branch again. I've removed debug symbols and the uncompressed size is now ~19MB.

**Comment by wonderdogone** [comment]
@emmanuelmillionaer So to run this on AWS lambda are you including the dependency on vips in the zip?

**Comment by jaycomito** [comment]
Hello @lovell, I'm having issues trying to set sharp up in AWS. I've referenced the sharp#look branch and I'm not sure if there's another step to handle the vips other than "npm install"? I saw you make a note of including the preinstall.sh and running that just notes "Found libvips 8.1.1". Thanks for your help.

**Comment by lovell** [comment]
@jaycomito Using the `look` branch means you no longer have to run the sudo-requiring `preinstall.sh` script.

Feel free to provide AWS error messages etc. here if you're having problems - I'm sure we can try to help.

**Comment by lovell** [comment]
I'll be closing this question soon as the master branch, soon to be released as v0.12.0, *should* work with AWS Lambda.

I'd very much appreciate confirmation of this from anyone that has been able to do so.

**Comment by lovell** [comment]
v0.12.0 now available via npm
