### ISSUE TITLE
Batch resize images optimisation. 

### ISSUE THREAD

**Issue by Daeamon** [lovell/sharp#3034]
Hello, i have 700 images same size (700x700) and i need to resize them all to 4396x2198. Is there some way to store transformation matrix and use it to speed up the process of resizing?

Example of code:
```typescript
export class Mem {
    static sharp = require('sharp');
}
export async function Resize(fromImageTemp: Buffer, diam: number = 700) {
    const needWidth = Math.round(Math.PI * diam) * 2;
    const needHeight = Math.round(needWidth * 0.5);
    const resizedBuffer = await Mem.sharp(fromImageTemp)
        .resize({
            width: needWidth,
            height: needHeight,
            kernel: Mem.sharp.kernel.lanczos3,
            fit: 'fill'
        })
        // output the raw pixels
        .raw()
        .toBuffer();
    return resizedBuffer;
}
```

**Comment by lovell** [comment]
I'm not sure what you mean by "store transformation matrix" as I assume these images are all different.

Did you try checking/setting https://sharp.pixelplumbing.com/api-utility#concurrency ?

In addition, if `fromImageTemp` will contain compressed image data, then decoding these may be the bottleneck rather than resizing.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
