### ISSUE TITLE
Sharp crashes with invalid opcode in libvips-cpp.so.42

### ISSUE THREAD

**Issue by idmacdonald** [lovell/sharp#3047]
Sharp is a dependency of the Ghost CMS, used to resize image file uploads. But I am finding that sharp causes Ghost to crash when images are uploaded to the latest Ghost on Ubuntu and Debian.

I take a fresh Ubuntu focal installation and then follow the instructions at https://ghost.org/docs/install/ubuntu/ to install Ghost. That gives me Sharp version 0.29.3 running on NodeJS 16.13.2.

Ghost is up and running fine, but uploading an image to be resized causes Ghost to crash with the kernel trapping the following error:
`ghost kernel: [248127.445076] traps: node[190951] trap invalid opcode ip:7f51fe938dfb sp:7ffcdffdfd60 error:0 in libvips-cpp.so.42[7f51fe62b000+aac000]`

The problem occurs with any image upload, all calls to sharp to resize an image result in the invalid opcode error listed above.

What is the output of running `npx envinfo --binaries --system`?

System:
    OS: Linux 5.4 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (8) x64 AMD Opteron(tm) Processor 6128
    Memory: 1.42 GB / 7.80 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.13.2 - /usr/local/bin/node
    npm: 8.1.2 - /usr/local/bin/npm

Here's the output from `cat /proc/cpuinfo`:

web101@ghost:~$ cat /proc/cpuinfo 
processor       : 0
vendor_id       : AuthenticAMD
cpu family      : 16
model           : 9
model name      : AMD Opteron(tm) Processor 6128
stepping        : 1
microcode       : 0x10000d9
cpu MHz         : 2000.018
cache size      : 512 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 5
wp              : yes
flags           : fpu de tsc msr pae mce cx8 apic mca cmov pat clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt lm 3dnowext 3dnow rep_good nopl cpuid extd_apicid pni cx16 popcnt hypervisor lahf_lm cmp_legacy abm sse4a misalignsse 3dnowprefetch vmmcall
bugs            : tlb_mmatch fxsave_leak null_seg amd_e400 spectre_v1 spectre_v2
bogomips        : 4000.03
TLB size        : 1024 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 48 bits physical, 48 bits virtual
power management:

There are 7 more vCPUs listed, but their specs are the same as above. Let me know if it would be useful to have the full output.

**Comment by lovell** [comment]
Please see #2723 (AMD Opteron 6128 CPUs were manufactured in or around 2010).

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.

**Comment by idmacdonald** [comment]
Hi, yes it's clear to me now.

Running the system on a newer CPU has fixed the problem. Given that others seem to have had the same problem, I wonder if the CPU requirement should be listed somewhere on the project's README.md page.

**Comment by lovell** [comment]
Added via commit https://github.com/lovell/sharp/commit/24150eac897a31a18959580fbe3d441702661826

**Comment by idmacdonald** [comment]
Excellent, cheers!

**Comment by ivucica** [comment]
Given #2723 explains that building a custom binary helps, I'm asking for no changes.

However, **since this is a top result for a search query involving the `trap invalid opcode` message from the original report**, I'll post a few quick notes here anyway, for future readers:

- Next.js or some other dependency seems to be pulling in this library -- in my use case, I merely want to serve a web UI which doesn't specify `sharp` as a dependency in its `package.json`
    - I have a nice-form-factor-but-everything-else-too-ancient HP Gen7 microserver serving as my home NAS. There are many flaws: abysmally slow, somewhat noisy, no UEFI, likely energy inefficient, suspend doesn't actually suspend a lot of the hardware -- but it's still functional, and for now it's my 24/7 machine. 
    - Problem is, of course, that it has an ancient `AMD Turion(tm) II Neo N54L Dual-Core Processor`. (Same as #3743 apparently.)
- `npm` package seems to have pulled in `./node_modules/sharp/vendor/8.14.5/linux-x64/lib/libvips-cpp.so.42`
- Debian version I run has the package `libvips42`; installing it has deployed the library in `/usr/lib/x86_64-
linux-gnu/libvips.so.42`, but just installing it did not help.

    Looks like the web UI I'm running does image operations upon first visit of the `/`. Before running `npm run chat` to spin up the software I'm trying to run, I tried setting the `LD_PRELOAD` envvar:

    ```bash
    export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libvips.so.42
    npm run chat
    ``` 

    but to no avail. Perhaps it's dynamically loaded with `dlopen()` preferring the built version? Perhaps I made a typo? In any case, I gave up on this version and did not check how the vendored version gets loaded.
- After installing the Debian version of `libvips42` and `libvips-dev`, after running `npm install --reinstall sharp`, it looks like I got a version that has no `libvips-cpp.so.42` in `vendor`.
- However there's still `@img/sharp-libvips-linux-x64/lib/libvips-cpp.so.42`. Looks like it was used (`export LD_DEBUG=libs`) if there's no `LD_PRELOAD`:

    ```
       1212748:     find library=libvips-cpp.so.42 [0]; searching
   1212748:      search path=/path/to/project/node_modules/@img/sharp-
linux-x64/lib/../../sharp-libvips-linux-x64/lib/tls/x86_64/x86_64:/path/to/project/node_modules/@img/sharp-linux-x64/lib/../../sharp-libvips-linux-x64/lib/tls/x86_64:...
    ...
    ...
   1212748:     calling init: /path/to/project/node_modules/@img/sharp
-linux-x64/lib/../../sharp-libvips-linux-x64/lib/libvips-cpp.so.42
    ```

    This causes a crash.

- However, this version does **not** get loaded if I reapply the `LD_PRELOAD` fix from above. After:

    ```
       1217840:     calling init: /path/to/project/node_modules/@img/sharp
-linux-x64/lib/sharp-linux-x64.node
    ```

    the correct binary is loaded.

Looks like this would have also impacted me if I finished my install of bluesky-pds.

Future readers who use Debian 12 would likely most easily resolve this by `apt install libvips42 libvips-dev`, removing either `node_packages` of the affected project or just `node_packages/sharp`, and reinstalling deps / rebuilding the Node project as usual.

I don't know how or whether to better document this, given how ancient this CPU is and given support for it still exists (just not in the vendored nor `@img/sharp*` binaries).

It'd be really nice if using the optimized codepaths was a runtime decision, but it is what it is. Thank you for your work in any case!

**Comment by lovell** [comment]
Commit https://github.com/lovell/sharp/commit/3fd818c4b59b055ce60ebc8938297ad69cc2e1e8 adds a runtime check for the v2 microarchitecture when using the linux-x64 prebuilt binaries and throws an error instead of crashing the process when not found. This will be in v0.34.0.
