### ISSUE TITLE
Add support for timeout when writing animated WebP

### ISSUE THREAD

**Issue by adityapatadia** [lovell/sharp#3068]
I am trying to convert this GIF to WebP. I used the `.timeout({seconds1:})` functionality of sharp but it never times out. Is there some issue with timeout and GIF processing?

https://user-images.githubusercontent.com/1086617/133960736-0cc21414-5d8f-4809-add0-16a4d7c22246.gif

**Comment by lovell** [comment]
This is probably due to the way the WebP writer in libvips reports its progress per frame rather than the output as a whole.

You can see this in action by removing the comment from this line and re-compiling sharp:

https://github.com/lovell/sharp/blob/83bb6a45542cbced5d68a258070f256f6ca8cee3/src/common.cc#L636

If you use GIF output via the new GIF writer, it reports progress based on the output image as a whole and respects timeout.

A PR to libvips to improve progress reporting in its WebP writer would be welcome, if you're able.

**Comment by adityapatadia** [comment]
Okay, I am not able to add as I don't understand libvips. It's not blocker for us so I would leave it to you and @jcupitt.

**Comment by jcupitt** [comment]
Hi @adityapatadia, 

Unfortunately, libwebp still doesn't support progressive writing, so this is not possible. It was a planned feature (large image support was too), but Google have mostly abandoned libwebp and I doubt if it will ever happen. If possible, I would move to a more modern and better supported image format.

**Comment by adityapatadia** [comment]
Understood. We already moved to AVIF but I think animation support is limited there. Anyway thanks for your quick response. If this is not going to be resolved, feel free to close this issue.
