### ISSUE TITLE
arm64, palette-based PNG input, Incorrect checksum for freed object

### ISSUE THREAD

**Issue by headfire94** [lovell/sharp#3222]
## Possible bug

Randomly throws error
```
node(35349,0x170cab000) malloc: Incorrect checksum for freed object 0x114018800: probably modified after being freed.
Corrupt value: 0x709090907090909
node(35349,0x170cab000) malloc: *** set a breakpoint in malloc_error_break to debug
```

Or
`[1]    35277 segmentation fault  node index.js`

### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```

  System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 1.53 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.9.1 - ~/.nvm/versions/node/v16.9.1/bin/node
    Yarn: 1.22.18 - /opt/homebrew/Cellar/yvm/4.1.4/shim/yarn
    npm: 7.21.1 - ~/.nvm/versions/node/v16.9.1/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  npmPackages:
    sharp: ^0.30.4 => 0.30.4 
  npmGlobalPackages:
    sharp: 0.30.4

```

### What are the steps to reproduce?

`git clone https://github.com/headfire94/sharp-bug-report`
`node index.js` - few times

### What is the expected behaviour?

generate compressed PNG

**Comment by headfire94** [comment]
Problem can be solved by removing Buffer usage. But i need it in my project to re-write existing files (sharp doesn't allow to write to the same file without this step)

**Comment by lovell** [comment]
Are you using the prebuilt libvips binaries provided by sharp, or are you relying on a globally-installed vips, perhaps via homebrew? What's the output of the following?
```sh
node -p "require('sharp').vendor"
node -p "require('sharp').versions"
```
Do you still see this behaviour if you remove the `quality: 90` option from `png()`?

**Comment by headfire94** [comment]
> Are you using the prebuilt libvips binaries provided by sharp, or are you relying on a globally-installed vips, perhaps via homebrew

IDK, but i installed `sharp` in project and globally.

The result of commands:
```
{ current: 'darwin-arm64v8', installed: [ 'darwin-arm64v8' ] }
```
```
{
  aom: '3.2.0',
  cairo: '1.17.4',
  cgif: '0.1.0',
  exif: '0.6.24',
  expat: '2.4.4',
  ffi: '3.4.2',
  fontconfig: '2.13.94',
  freetype: '2.11.1',
  fribidi: '1.0.11',
  gdkpixbuf: '2.42.6',
  glib: '2.71.1',
  gsf: '1.14.48',
  harfbuzz: '3.3.1',
  heif: '1.12.0',
  imagequant: '2.4.1',
  lcms: '2.13',
  mozjpeg: '4.0.3',
  orc: '0.4.32',
  pango: '1.50.3',
  pixman: '0.40.0',
  png: '1.6.37',
  'proxy-libintl': '0.3',
  svg: '2.52.5',
  spng: '0.7.1',
  tiff: '4.3.0',
  vips: '8.12.2',
  webp: '1.2.2',
  xml: '2.9.12',
  'zlib-ng': '2.0.6'
}
```

> Do you still see this behaviour if you remove the quality: 90 option from png()?

No, works fine

**Comment by lovell** [comment]
> IDK, but i installed sharp in project and globally.

Thanks for the info, it looks like you're using the prebuilt binaries for ARM64 (which are cross-compiled on x64) and the problem only occurs when using palette-based PNG output.

Please can you try GIF-based output, which also uses quantisation, to see if that has a similar behaviour.

```diff
-  .png({ compressionLevel: 9, quality: 90 })
+  .gif()
```

In addition, please can you try removing the global installation of sharp, so there's only one local sharp package installed, just in case there's some kind of conflict between the two.

**Comment by headfire94** [comment]
> In addition, please can you try removing the global installation of sharp, so there's only one local sharp package installed, just in case there's some kind of conflict between the two.

looks like not related. still fails.

With Gif works fine

**Comment by lovell** [comment]
Thanks for the extra info, are you able to reproduce on any other machine that does not have an M1 Max CPU?

The sharp unit tests run on an M1 mac mini and I'd expect them to fail randomly in a similar manner, which they don't. I'd also expect more people to have run into this by now if it affected all M1 devices.

The fact that GIF output works OK suggests this problem is occurring somewhere between libvips+libimagequant+libpng, rather than libimagequant itself.

https://github.com/libvips/libvips/blob/9cbc361269cedd5ddadd9695d7aa3368daa31d24/libvips/foreign/vipspng.c#L1188-L1251

My best guess right now is that there's a problem with memory de/allocation/corruption that occurs only when outputting palette-based PNG images using a cross-compiled libvips, libimagequant and libpng, and only when run on an M1 Max.

**Comment by lovell** [comment]
Given the input is an RGBA PNG, are you able to recreate this with a non-transparent RGB image i.e. without an alpha channel? Thank you for your help narrowing this down.

**Comment by headfire94** [comment]
Unfortunately, i don't have another machine near me.

Alpha channel looks like isn't related. i tried 2 different PNG with alpha channel but only original one fails
https://github.com/headfire94/sharp-bug-report/commit/711dc8e8883c58ad6c32eea2c9369db0fcaa1edb

**Comment by lovell** [comment]
Thanks, that's interesting, we're getting closer, as `image.png` (fails) has an 8-bit palette whereas `image-2.png` (works) is full 32-bit colour.

Are you able to check other palette-based input, such as [swiss.png](https://raw.githubusercontent.com/lovell/sharp/main/test/fixtures/swiss.png) as used by the unit tests?

https://github.com/lovell/sharp/blob/83bb6a45542cbced5d68a258070f256f6ca8cee3/test/unit/png.js#L131-L135

It doesn't seem to affect non M1 Max platforms (or at least I've not been able to reproduce) so my best guess is this could be a cross-compiler bug. I wonder if the first image is being re-quantised to exactly 256 palette entries and introducing the potential for an off-by-one error somewhere?

**Comment by headfire94** [comment]
`swiss.png` works fine for me.
`npm run test-unit` in this repo works fine.

[Added](https://github.com/headfire94/sharp-bug-report/commit/e3b05825c53484906c61365fd8cdebc70fa621d8) fixtures in my repo. fails on this [one](https://github.com/headfire94/sharp-bug-report/blob/e3b05825c53484906c61365fd8cdebc70fa621d8/for-test/embed-4-into-4.png)
```
embed-4-into-4.png
node(59638,0x170843000) malloc: Incorrect checksum for freed object 0x144e0cb90: probably modified after being freed.
Corrupt value: 0x71694c0071694c
node(59638,0x170843000) malloc: *** set a breakpoint in malloc_error_break to debug
```

**Comment by pburke** [comment]
I added Sharp latest to my next.js project yesterday and am also seeing this error locally (M1 Mac) but not in production.

**Comment by lovell** [comment]
@headfire94 Thank you, the `embed-4-into-4.png` image is full-colour, so that helps rule out palette-based input as a possible source of the problem.

Does making the following change still fail (ideally we want the simplest possible reproduction)?
```diff
- .png({ compressionLevel: 9, quality: 90 })
+ .png({ palette: true })
```

@pburke Please can you confirm exactly which CPU you're using, that you see the same behaviour from https://github.com/headfire94/sharp-bug-report/ and also provide one or more additional input images that consistently fail in this manner.

**Comment by headfire94** [comment]
i can confirm that it still fails with 
```diff
- .png({ compressionLevel: 9, quality: 90 })
+ .png({ palette: true })
```

**Comment by lovell** [comment]
I think what we're seeing here is an effect of #3225

The problem in this issue only occurs on CPUs that provide NEON (i.e. arm64), with some palette-based PNG inputs and always palette-based PNG output.

The use of palette-based output forces libvips to decompress the whole image into memory at once, rather than stream smaller regions, and I think this difference is just enough to trigger the (1 byte, I think) buffer overflow of #3225

The forthcoming v0.31.0 of sharp will provide prebuilt binaries that use the latest libspng with the fix. In the meantime, you might be able to workaround this by using `brew install vips` first, which should install libspng v0.7.2.

**Comment by lovell** [comment]
Let's track this at #3225

**Comment by cfxd** [comment]
> `brew install vips`

Worked like a charm for me, thanks!
