### ISSUE TITLE
Retain original colorspace

### ISSUE THREAD

**Issue by AlessioGr** [lovell/sharp#3339]
### What are you trying to achieve?
I'd like the output to have the same colors / colorspace as the original image. Some outputs from, let's say AdobeRGB, look washed out with less saturated colors than the original image.
Now, I also can't just use `.pipelineColourspace('rgb16').toColorspace("rgb16")` as that would make simple sRGB images too saturated. It should just retain the original colorspace.

How can I do that? I found a few issues about that, though it seems they were all closed / fixed. Didn't find a solution for that, though.

Edit: same thing would also be nice with format & quality setting. So, no matter if the input is png or jpg, it would output a png / jpg with the same (or best) quality setting - not worse

**Comment by lovell** [comment]
Hi, AdobeRGB is a colour profile rather than a colour space. A pipeline colour space of `scrgb` might be suitable for your needs.

Did you see [withMetadata](https://sharp.pixelplumbing.com/api-output#withmetadata), which allows a custom output colour profile?

For use of an existing input profile with the output, please see the future possible enhancement at #1323.

**Comment by RKTZ** [comment]
Hi, keeping the original colour profile would be nice instead of having to provide a .icc file. I also would like to keep my adobe RGB profile.

**Comment by lovell** [comment]
Let's track this at #1323
