### ISSUE TITLE
Dedupe libvips-42.dll for windows users

### ISSUE THREAD

**Issue by Pomax** [lovell/sharp#3402]
## Feature request

As Windows doesn't come with libvips, Sharp convenient bundles it in as a .dll file, but it bundles it in _twice_: once in `build/release` and then _again_ in `vendor/8.13.2/win32-x64/lib`. Given that it's a whopping 21Mb, deduplicating that would be an excellent idea. (The same applies to `libglib-2.0-0.dll`, `libvips-cpp.dll`, and `libgobject-2.0-0.dll`, which take up a combined additional 2Mb)

The two most obvious options I can think of would be:

- remove the `vendor` dir from the Windows build before packing up the release, or
- make the .dll files in `build/release` Windows symlinks instead of real files.

Either would cut the Windows release size in half.

**Comment by lovell** [comment]
At `npm install` time, sharp ensures the DLLs have been extracted to `vendor` then copies them to `build` (so they exist in the same directory as the prebuilt binary for sharp itself), which is primarily to ensure these files survive a rebuild.

The logic for this Windows-specific behaviour is in https://github.com/lovell/sharp/blob/main/install/dll-copy.js

There used to be (permission?) problems in the past with Node.js and symlinks on Windows, but perhaps we could experiment using a "junction" for this?

**Comment by Pomax** [comment]
how long ago are we talking? Because windows has two types of symlinks - junctions, which generally need admin rights to create, and "plain symlinks" which don't.

**Comment by lovell** [comment]
My Windows knowledge is rather limited, but my understanding is that junctions can be created by a local, non-elevated user, but symlinks might require local admin rights, at least on NTFS.

Sadly "junctions" won't help here as they are for directories only, where we are dealing with individual files. (The fix for the Node.js ecosystem was via https://github.com/libuv/libuv/pull/1706 and has been available since version 10.)

If we are to use symlinking, it would be best to retain the copying logic as a fallback should it fail.

**Comment by Pomax** [comment]
In that case I guess the question is "why does the vendor directory need to hang around?". The dll files are not tied to Node version, so making the node-gyp process look for them in the `build/release` dir should be fine?

**Comment by lovell** [comment]
When `npm install --build-from-source` is run, the `build` directory is removed, so we need to have these somewhere else on the filesystem to support this development use case.

We could test for `process.env.npm_config_build_from_source` and use the existing copy approach when present, otherwise use a rename? Happy to accept a PR for this, if you're able.

**Comment by Pomax** [comment]
never tried anything gyp related (other than filing issues to please add python 3 support back in the 2.7 days =) but I can have a look?

**Comment by Julusian** [comment]
How will removing these duplicate files interact with prebuild-install?

It is not uncommon for prebuild-install to be run each time an electron build is produced.
In one project I have made it manually invoke the postinstall commands, to allow for cross-compiling the electron app https://github.com/bitfocus/companion/blob/master/tools/build_prepare.mjs

**Comment by lovell** [comment]
This will probably be superseded by https://github.com/lovell/sharp/issues/3750

**Comment by lovell** [comment]
This problem has gone away with the release of sharp v0.33.0 - all that custom download and file copying logic has been removed.
