### ISSUE TITLE
Optimizing multi output performance?

### ISSUE THREAD

**Issue by louisondumont** [lovell/sharp#3407]
Hi,

I'm trying to resize my files then save them under 3 different formats (original, webp, avif).

I'm using .clone() to resize the picture only once, then save it under 3 different formats 

    const original = sharp(fileName, {failOnError: false});
    const sharpResized = original.clone().resize(width, height, {fit: 'outside'});
  
    promises.push(sharpResized.clone().toFile(outputFilename));
    promises.push(sharpResized.clone().webp().toFile(outputFilenameWebp));
    promises.push(sharpResized.clone().avif().toFile(outputFilenameAvif));

But I'm still getting pretty slow performances, it takes about 400ms to save 3 files and takes 100% CPU on 8 cores (I'm running this over millions of pictures).

Does the .clone() feature do what I assume it does: resizing the image only once, then reusing the resized image in memory to output 3 files?
Is there any other way to optimize performances for this type of batch processing with multi output that I'm not aware of?

Thanks!

**Comment by lovell** [comment]
`clone()` is for Stream-based output, so won't help you here.

For filesystem input and output where there are "millions of pictures", try to process multiple input images concurrently, rather than multiple output images, to improve the hit rate of libvips operation cache (e.g. generate the WebP then the AVIF for a given input).

My best guess would be that AVIF encoding is taking the vast majority of CPU time anyway, so perhaps try setting its `effort` parameter.

https://sharp.pixelplumbing.com/api-output#avif

**Comment by louisondumont** [comment]
Thanks. I will disable AVIF compression for now as the performances have indeed skyrocketed after removing it.
