### ISSUE TITLE
Install script creates a symbolic link which fails in virtual machines on windows

### ISSUE THREAD

**Issue by jaubourg** [lovell/sharp#348]
I use vagrant for windows. Everything works fine with `0.12.1` but in `0.12.2` the install script now attempts to create a symbolic link for some header file resulting in the following error:

```
ERROR: EPROTO: protocol error, symlink 'libpng16/pngconf.h' -> '/vagrant/node_modules/sharp/include/pngconf.h'
```

I use `npm --no-bin-links install` to avoid this kind of issues. Could the install script check if the option was used (provided it is even possible) or could it not create a symbolic link?

Thanks :)

**Comment by lovell** [comment]
Bonsoir, since v0.12.1 sharp will fetch and use a pre-built copy of libvips if the minimum required version is not already available globally.

v0.12.2 of sharp required v8.2.0 of libvips so my best guess is that you've got a global version of libvips < v8.2.0. If so, the quick fix for this is to globally install libvips v8.2.0+

There's a possibly-related bug filed against Virtualbox at https://www.virtualbox.org/ticket/14563

**Comment by jaubourg** [comment]
And you're perfectly right, problem solved. Merci, sir, and sorry for having taken of your time ;)

**Comment by lovell** [comment]
De rien.
