### ISSUE TITLE
npm tests warning - OSX 10.10.5

### ISSUE THREAD

**Issue by keithics** [lovell/sharp#352]
I can getting these warnings.. when running npm test (Node v5.2.0)

	vips warning: jpegload_buffer: no property named `density'

	vips warning: jpegload_buffer: no property named `density'

	vips warning: jpegload_buffer: no property named `density'

	vips warning: jpegload_buffer: no property named `density'

	jpeg-cubic sharp-buffer-file x 12.41 ops/sec ±2.34% (59 runs sampled)

	vips warning: jpegload_buffer: no property named `density'

	vips warning: jpegload_buffer: no property named `density'

	vips warning: jpegload_buffer: no property named `density'

	vips warning: jpegload_buffer: no property named `density'

**Comment by lovell** [comment]
Hello, the `ops/sec` bit suggests these are the benchmark tests rather than functional tests. Perhaps set the `VIPS_WARNING=0` environment variable like https://github.com/lovell/sharp/blob/master/package.json#L26

There is one failing functional test on OS X at the moment - see https://travis-ci.org/lovell/sharp-osx-ci/builds/106839560

**Comment by keithics** [comment]
:+1:  thank you.

**Comment by lovell** [comment]
Commit 736c04a should make things a little quieter, thanks for reporting!

**Comment by lovell** [comment]
Also, all tests passing on OS X again https://travis-ci.org/lovell/sharp-osx-ci/builds/106839560
