### ISSUE TITLE
Rounding of decimal heights and widths, JPEG shrink-on-load

### ISSUE THREAD

**Issue by Asheboy** [lovell/sharp#3526]
In the following I'm resizing a 500x399 image:

```
const sharp = require('sharp')

sharp('500x399.jpeg')
  .resize({ width: 100 })
  .toFile('output')
  .then((info) => console.log(info))
```

The output of `info` is:

```
{
  format: 'jpeg',
  width: 100,
  height: 79,
  channels: 3,
  premultiplied: false,
  size: 3837
}
```

If you do the maths (100/500 * 399) the 'exact' height would be 79.8, which obviously a standard rounding would take to 80. Is there an option in sharp that would allow it to round this way?

I know it doesn't mean anything, but both ImageMagick and GraphicsMagick will both produce a 100x80 image when passed `-resize 100`.

Input image:
![500x399](https://user-images.githubusercontent.com/1822529/211919896-592b3558-8737-4a54-9889-1b0e45425bfa.jpeg)

Thanks!

Edit: I've actually just tried this on a similar png and it is resized to 100x80, so I'm not really sure why it's rounding down for the jpeg. Example PNG below:
![500x399](https://user-images.githubusercontent.com/1822529/211927331-7419db4f-822b-4713-9d27-9ceb515405c0.png)

**Comment by lovell** [comment]
This looks like a rounding error due to JPEG shrink-on-load.

In this specific example the underlying libjpeg-turbo logic is rounding 399 / 4 = 99.75 down to 99 rather than up to 100. libvips then scales down by a further 1.25 to reach the target width of 100, however as you've seen 99 / 1.25 = 79.2, rounding to 79.

You can reduce the influence shrink-on-load has in resizing with `fastShrinkOnLoad`.

https://sharp.pixelplumbing.com/api-resize

```diff
-  .resize({ width: 100 })
+  .resize({ width: 100, fastShrinkOnLoad: false })
```

Or, if you always know both output dimensions up front, then you can request them explicitly:
```diff
-  .resize({ width: 100 })
+  .resize({ width: 100, height: 80 })
```

**Comment by lovell** [comment]
I added a note to the docs about possible round-down when auto-scaling via commit https://github.com/lovell/sharp/commit/9f79f80a9364669f74b6bbb57cfca5698d0d3924

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.

**Comment by Asheboy** [comment]
> I hope this information helped. Please feel free to re-open with more details if further assistance is required.

Yes it did! Thank you!
