### ISSUE TITLE
License issue with underlying libvps

### ISSUE THREAD

**Issue by dgaiero** [lovell/sharp#3565]
### What are you trying to achieve?

I am looking at the license of sharp and see that it is Apache 2.0, however an underlying dependency vips is LGPL. (https://github.com/lovell/sharp/blob/main/src/libvips/cplusplus/VConnection.cpp#L6-L21). Is this an issue and a conflict with the Apache 2 license of Sharp?

### When you searched for similar issues, what did you find that might be related?

No related issues

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

See https://github.com/lovell/sharp/blob/main/src/libvips/cplusplus/VConnection.cpp#L6-L21

### Please provide sample image(s) that help explain this question

N/A

**Comment by dgaiero** [comment]
Thanks, that answers my question.

**Comment by lovell** [comment]
As a result of this question, I carried out a full audit of libvips' dependencies to ensure nothing had changed since I last checked. This uncovered some ambiguity around libgsf licensing, which I've since determined is officially LGPL-2.1-only, so from the next release the prebuilt binaries will remove this.

https://gitlab.gnome.org/GNOME/libgsf/-/issues/28
