### ISSUE TITLE
Sharp installation problem in GCP VM instance, ETIMEDOUT

### ISSUE THREAD

**Issue by damario789** [lovell/sharp#3573]
Hi, I have a problem installing sharp in the GCP VM

When I execute `npm install`, It shows the result in the pic below
![image](https://user-images.githubusercontent.com/81469594/221529693-f7933e6e-fcff-44a8-b5af-9a1f3d7bb324.png)

Is there any solution for this issue?

**Comment by lovell** [comment]
Did you see the bit that says `ETIMEDOUT`? This means there is/was a networking problem between the machine this came from and GitHub servers.

As an aside, the issue template was ignored/deleted when creating this issue. In future, please ensure all questions are answered, and that any logs provided are text-based rather than using screenshots, as text is much easier to read/parse/verify.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
