### ISSUE TITLE
Conversion to webp not working

### ISSUE THREAD

**Issue by MuhammadHadiofficial** [lovell/sharp#3652]
Hi, I'm trying to force the uploaded image to be converted into webp format before uploading to the s3 bucket. 
But after upload, I still see a jpg/png extension for images on s3 buckets.
![image](https://user-images.githubusercontent.com/31585104/235176798-6781cd1a-8e0f-479f-a30c-0854535eb16c.png)

Kindly, guide me in case anything is wrong here during upload or while converting to buffer?

**Comment by lovell** [comment]
Did you see https://sharp.pixelplumbing.com/api-output#webp ?

Param | Type | Default | Description
-- | -- | -- | --
[options.force] | `boolean` | `true` | force WebP output, otherwise attempt to use input format

By explicitly setting `force: false`, the format of the input will be respected and used.

(As an aside, please paste source code as text rather than screenshots as it's much easier to read.)
