### ISSUE TITLE
v0.32.0: huge AVIF output images cannot be opened in older software

### ISSUE THREAD

**Issue by 3xploiton3** [lovell/sharp#3701]
images cannot be open
![image](https://github.com/lovell/avif-cli/assets/19517680/ed879751-3b10-4d4a-9735-157a0bf9a28b)

i'm using default config

files:
https://drive.google.com/file/d/1sLXwxH0cdjnkwQ7higs_qHTUc3IFxgQI/view?usp=sharing

**Comment by lovell** [comment]
The prebuilt binaries provided by sharp v0.32.x include libaom v3.6.0. It looks like it has a bug relating to encoding very large AVIF images where the output is valid but uses new compression features ("level 7 and 8") that are not yet widely supported in older decoders, including Chrome.

https://aomedia.googlesource.com/aom/+/7f006ee7f3da90c86d1b05696a5feac4f4162ac9%5E%21/
https://www.mail-archive.com/kde-bugs-dist@kde.org/msg810055.html

This has been fixed in libaom v3.6.1, which a future version will include in prebuilt binaries.

**Comment by lovell** [comment]
The prebuilt binaries provided by sharp v0.32.4 include libaom v3.6.1 with the fix for this.
