### ISSUE TITLE
metadata(): format comes out as 'magick'

### ISSUE THREAD

**Issue by papandreou** [lovell/sharp#377]
```js
require('sharp')('testdata/animated.gif').metadata(console.log);
// ...
{ format: 'magick',
  width: 23,
  height: 20,
  space: 'rgb',
  channels: 3,
  hasProfile: false,
  hasAlpha: false }
```

I expected it to be `format: 'gif'`. I'm guessing the info is available somehow since the width and height are?

**Comment by lovell** [comment]
Hej Andreas, libvips knows that *magick could load the image, but has no further information about what codec/container it used.

The forthcoming v8.3.0 of libvips is about to get much-improved GIF support and #369 should provide what you're looking for. I'll probably stop bundling the *magick loader too, so this unexpectedly expected behaviour should disappear entirely.

**Comment by papandreou** [comment]
Okay, thanks. That's good enough for me :)

**Comment by papandreou** [comment]
@lovell, actually, a quick follow-up question -- will the improved GIF support add the ability to detect an animated gif via `.metadata(...)`?

**Comment by lovell** [comment]
@papandreou Not sure yet, will add an investigation as part of #369.

**Comment by papandreou** [comment]
@lovell Thanks a lot :)
