### ISSUE TITLE
How to ingrate Sharp to Nuxtjs

### ISSUE THREAD

**Issue by vanminhquangtri** [lovell/sharp#3787]
Hello,

I have an app Nuxt3 and I want to integrate Sharp to my Nuxt app to optimize image, mainly for resize image for each breakpoint.
I can't find documentation to this on your website.

Can you please show me the link for documentation or instruct me how to integrate Sharp to Nuxt3?

Thank you

**Comment by lovell** [comment]
Did you see https://image.nuxt.com/providers/ipx ?

**Comment by vanminhquangtri** [comment]
@lovell yes I already read it. 
IPX only work on localhost, all images work. But when deploy my website to AWS, all images are not rendered. I seems IPX not compatible with AWS because many people have the same problem with me. It also not work with Netlify either.
So I am trying to integrate directly Sharp to my Nuxt instead of using IPX.
Thank you.

**Comment by lovell** [comment]
> seems IPX not compatible with AWS because many people have the same problem with me

There are zero issues when searching for AWS in the [ipx repo](https://github.com/unjs/ipx).

https://github.com/search?q=repo%3Aunjs%2Fipx+%28AWS+OR+Amazon%29&type=issues

>  It also not work with Netlify either.

Did you see https://image.nuxt.com/providers/netlify ? What did Netlify say when you asked them?

The summary here is that you will almost certainly be better off using all the great work already done by the Nuxt team rather than rolling your own solution.

**Comment by vanminhquangtri** [comment]
Thank you @lovell . I have not checked with netlify. I think there would be some problem with my codes.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
