### ISSUE TITLE
Usage of minSize in webp

### ISSUE THREAD

**Issue by NeilXjz** [lovell/sharp#3863]
Hello, I would like to ask you about the specific usage of minSize in webp. When I compress a webp with animation, the number of frames does not change regardless of whether the minSize parameter is set or not.

I hope that I can reduce the number of frames of webp animation through certain parameters. I don’t know if I can use this parameter.

**Comment by lovell** [comment]
https://sharp.pixelplumbing.com/api-output#webp

> prevent use of animation key frames to minimise file size (slow)

This setting does not reduce the frame count, but rather prevents any given frame from being considered a [key frame](https://en.wikipedia.org/wiki/Key_frame), so that only the delta between the previous and the next frame is stored.

Perhaps you could explain more about the problem you're trying to solve?
