### ISSUE TITLE
v0.33.0: allow installation of precompiled binaries with yarn@1

### ISSUE THREAD

**Issue by ForsakenHarmony** [lovell/sharp#3871]
### What are you trying to achieve?

`yarn add sharp` with yarn `v1.22.19`

Is there any reason to not allow installation with yarn 1?

**Comment by lovell** [comment]
You may need to add the `--ignore-engines` flag for old versions of yarn.

Please see https://github.com/lovell/sharp/issues/3750 for the full context.

**Comment by mceachen** [comment]
@lovell Just (tried to) upgrade to 0.33.0, but I'm on yarn (v1), and the binary dependency didn't get pulled in (even with a `supportedArchitectures` section added to my `package.json`).

I'd suggest perhaps adjusting your installation verbiage from "yarn v3 is recommended" to "yarn v1 won't work, move to greener pastures" (or something more diplomatic).

**Comment by lovell** [comment]
yarn v1 has been in maintenance mode for [almost 4 years](https://dev.to/arcanis/introducing-yarn-2-4eh1#what-will-happen-to-the-legacy-codebase). I understand people were (quite rightly) hesitant to upgrade yarn due to all the problems with "plug'n'play", but that feature can and should be switched off by setting [nodeLinker](https://yarnpkg.com/configuration/yarnrc#nodeLinker) to any value other than the default.

Using the `--ignore-engines` flag with v1 will probably work for many scenarios, but it will download every binary for every platform, which is a huge waste of time, energy, bandwidth etc. If you care about energy conservation then please upgrade to a modern package manager.

For those looking to use yarn for cross-platform installs via its `supportedArchitectures` feature, that was added in its [v3.1.0](https://yarnpkg.com/advanced/changelog#310) release.

**Comment by lovell** [comment]
I've updated the docs via commit https://github.com/lovell/sharp/commit/004fff975ff5f3a933aebd15631fe12ed0c80035

If you're using yarn v1 please upgrade and set `nodeLinker` to anything other than `pnp`.
