### ISSUE TITLE
Continuation of #3870 - error Could not load the "sharp" module using the linux-x64 runtime

### ISSUE THREAD

**Issue by felixsanz** [lovell/sharp#3923]
This is a continuation of the locked #3870 thread, where is said that this only affects vercel.

That's not true. I've pushed my code to GitHub and GitHub actions suffer the same issue. It can't build my repo because sharp 0.33.1.

Probably many other suffer this issue.

**Comment by fgrabenstaetter** [comment]
Hello,
I have the same issue with the linux-x64 runtime.
This seems to be a general issue, I confirm !

**Comment by lovell** [comment]
#3870 relates to a problem specific to Vercel. Other problems may exhibit similar effects but with different causes. The issue is locked as it was attracting comments conflating effects rather than causes.

As requested in #3870 please [open a new installation issue](https://github.com/lovell/sharp/issues/new?assignees=&labels=installation&projects=&template=installation.md) and answer all the questions. I need your answers to these questions as a minimum starting point to be able to try to help you.

**Comment by ywzhaiqi** [comment]
after install `@img/sharp-linux-x64`，work fine.
