### ISSUE TITLE
Override HEIC output limitation

### ISSUE THREAD

**Issue by igorescobar** [lovell/sharp#4030]
Hi,

I noticed the introduction on your changelog:
- Limit HEIF output dimensions to 16384x16384, matches libvips.

But it looks like this is a limit that can be overridden: https://github.com/libvips/libvips/discussions/3635

Is there any way I can override this limit to support what is described on the issue above? 

I'm getting this error for both HEIC and WebP:
- Processed image is too large for the WebP format
- Processed image is too large for the HEIF format

**Comment by lovell** [comment]
https://github.com/libvips/libvips/discussions/3635 refers to reading HEIF images but I think your question refers to writing HEIF images.

The reason for the output limit on HEIF is due to the most common decoders having a similar limit, e.g. web browsers won't display AVIF images greater than 16384x16384. If that limit has changed then we could consider doing likewise in libvips.

WebP has a limit of 16383x16383 as it only uses 14-bit dimensions.
