### ISSUE TITLE
How to get tiles into stream?

### ISSUE THREAD

**Issue by pzien** [lovell/sharp#474]
tile() method seems to return original image and dzi files and folder (or the zip file) seem to be a side effect of the call. How can I get the tiles without writing them to disk?
It would be nice to use it like that:
```
var transformer = sharp().tile();
readableStream.pipe(transformer).pipe(writableStream);
```
to get tiles into writableStream.

**Comment by lovell** [comment]
Hello, libvips only supports writing image pyramid tiles to disk.

I checked the [relevant docs](http://sharp.dimens.io/en/stable/api/#tileoptions) and they currently say "You can also use the file extension .zip or .szi to write to a ZIP container instead of the filesystem." This is confusing as the filesystem is still involved with ZIP output, sorry about that, I'll update this to be more explicit.

**Comment by pzien** [comment]
That's a pity... Thanks for a quick response!

**Comment by lovell** [comment]
Commit 4b98dbb hopefully removes some of the ambiguity from the docs - thanks for bringing this to my attention!

**Comment by liokm** [comment]
@lovell Does the situation change? I want to use Sharp in AWS Lambda to generate tiles from image around several GBs and upload to S3, but either `/tmp` (512MB at max) or memory (3GB at max) is limited.

**Comment by lovell** [comment]
Please see #2238
