### ISSUE TITLE
JPG to string/buffer and back again

### ISSUE THREAD

**Issue by schaeffer11** [lovell/sharp#576]
Hi there,

I am currently trying to pass a sharp image as a string (because it's over a message queue),  to another process which needs to reconvert it back to a sharp image. We saw the
#552  issue, which seemed similar, except we don't want to pass the raw data, it's several times the size of the jpg form. So, the question is: is there a way to convert a sharp image to a string (as a jpg), and then transform it back to a sharp image? Thank you!

**Comment by lovell** [comment]
> "is there a way to convert a sharp image to a string"

Hello, an instance of a `sharp` Object represents a series of operations that will be applied to an input image rather than any kind of "sharp image" itself.

The processing pipeline *starts* work on the input image when one of `toFile()`, `toBuffer()` or `pipe()` are called to access the output image.

Intermediate images are unavailable (and may never completely exist in memory at the same time anyway based on the way that libvips works).

From what is described here, passing the input JPEG data alongside another data structure representing the operations to be applied to it would probably make most sense.

**Comment by lovell** [comment]
Feel free to re-open if there are further, related questions.
