### ISSUE TITLE
Benchmarks produce images with different sizes and aspect rations

### ISSUE THREAD

**Issue by homm** [lovell/sharp#624]
ImageMagick & GraphicMagick:

![output jpg gm](https://cloud.githubusercontent.com/assets/128982/20278819/2878eb88-aab7-11e6-8536-6d32eb45618a.jpg)

jimp && mapnik:

![output jpg mapnik](https://cloud.githubusercontent.com/assets/128982/20278852/4c9ad74c-aab7-11e6-803b-9047c10a18fb.jpg)

sharp:

![output jpg sharp](https://cloud.githubusercontent.com/assets/128982/20278861/5538c166-aab7-11e6-9318-46332bdc7e08.jpg)

**Comment by lovell** [comment]
Thanks for alerting me to this; I'm unsure how this has gone unnoticed until now.

A quick way to make sure these tests are fairer is to use dimensions that match the aspect ratio of the original image.

Making this change:
```diff
-const height = 480;
+const height = 604;
```

...produces these results locally (i3-4170) for me:

```diff
- jimp-buffer-buffer x 1.25 ops/sec ±5.24% (11 runs sampled)
+ jimp-buffer-buffer x 1.23 ops/sec ±4.56% (10 runs sampled)
- lwip-buffer-buffer x 3.00 ops/sec ±1.79% (19 runs sampled)
+ lwip-buffer-buffer x 2.71 ops/sec ±1.82% (18 runs sampled)
- mapnik-buffer-buffer x 3.35 ops/sec ±3.70% (21 runs sampled)
+ mapnik-buffer-buffer x 3.32 ops/sec ±1.94% (21 runs sampled)
- gm-buffer-buffer x 5.53 ops/sec ±0.65% (31 runs sampled)
+ gm-buffer-buffer x 5.66 ops/sec ±0.26% (32 runs sampled)
- sharp-buffer-buffer x 34.03 ops/sec ±0.25% (79 runs sampled)
+ sharp-buffer-buffer x 32.18 ops/sec ±0.28% (76 runs sampled)
```
This suggests *magick is slightly faster (less shrinking = fewer CPU cache evictions?) and everything else is slightly slower. The greater sharp/libvips drop is probably due to the overall speed being limited by the JPEG encoder, which will have more work to do here.

I'll update these tests properly and re-run on EC2 hardware in the next day or so.

**Comment by homm** [comment]
Great! But why height is 604?

720 / 2725 * 2225 ≈ 588

:–)

**Comment by lovell** [comment]
D'oh! Will get it right when I fix this, thank you!

**Comment by homm** [comment]
> The greater sharp/libvips drop is probably due to the overall speed being limited by the JPEG encoder

No only. Unlike the others, sharp produced cropped image with requested size and preserved aspect ratio. As a result, an amount of processed source pixels was cut off.

**Comment by lovell** [comment]
Commit d7d03b1 updates the performance tests to use a height of 588 pixels and the latest test results are available at http://sharp.dimens.io/en/latest/performance/

Thanks again for reporting this!
