### ISSUE TITLE
Is it possible to get length/width parameters of the image before processing it?

### ISSUE THREAD

**Issue by Andriy-Kulak** [lovell/sharp#761]
Hi - I need image length and width parameters before processing. Is it possible to get them via sharp package? I couldn't find anything in documentation on this.

Thanks!
Andriy

**Comment by lovell** [comment]
Hello, the [metadata](http://sharp.dimens.io/en/stable/api-input/#metadata) operation is probably what you need.

**Comment by lovell** [comment]
Closing as I assume #785 indicates progress.

**Comment by michaellosurdo** [comment]
hey @lovell I'm not sure what just happened, but I believe the link in the "metadata" comment from April 9, 2017 is a bad URL that, after redirecting several times to the IP address "138.68.59.48", downloads a scary-looking HTML file... for reference, the linked URL is "http://sharp.dimens.io/en/stable/api-input/#metadata"... 

1. Do you have any idea what that is (and if those who clicked should be worried lol)? 
2. Is there any way to adjust the linked URL so that anyone googling "node sharp resize image" doesn't make the same mistake?

**Comment by lovell** [comment]
@michaellosurdo Thanks, have updated, please see #2132 for context.
