### ISSUE TITLE
Auto-rotate + flip/flop fails?

### ISSUE THREAD

**Issue by rexxars** [lovell/sharp#837]
Hi!

I think something has changed regarding flip/flop and rotation between 0.17 and 0.18. Previously, I was using the following code to first auto-rotate the image by EXIF orientation and then flop it:

```js
sharp('some-image.jpg').rotate().flop().toFile(...)
```

This doesn't seem to work in 0.18. The image is not flopped. The same goes for flipping.
If I explicitly define an angle in the `rotate()` call, things work as expected.

Any ideas?

**Comment by lovell** [comment]
Hello, it looks this behaviour was altered by commit 99810c0, which can overwrite existing `flip` and `flop` parameter values. I can take a look in a few days, or @ncoden might be able to help also.

**Comment by solfolango** [comment]
I just stumbled upon a non-working rotate() all by itself. I am adding this info to this thread instead of creating another one.

This code is not rotating a picture any longer:

```
sharp(__dirname + '/mocks/virtualcam/01.jpg')
    .rotate(180)
    .toFile(__dirname + '/rotated.jpg');
```

I came across this issue on a fresh install of 0.18.1, an older project using 0.17.3 is still somewhat working (I came across rotated and non-rotated images, always with `rotate(180)`, never `rotate()` but I thought that it had something to do with the camera settings (I am processing captures by a Canon EOS and there is some kind of orientation-EXIF), but seeing it kind of broken right now creates second thoughts.

**Comment by lovell** [comment]
Commit 49297d6 adds tests for auto-rotate and flip/flop, plus the fix. This will be in v0.18.2. Thanks for reporting.

**Comment by ncoden** [comment]
Sorry for the bug I introduced @lovell

**Comment by lovell** [comment]
@ncoden Pas de souci, il n'a pas eu un test.

**Comment by rexxars** [comment]
Thanks for the fix :)

**Comment by ncoden** [comment]
@lovell _How does everybody find out i'm French ?_ ;)

**Comment by lovell** [comment]
v0.18.2 now available.
