### ISSUE TITLE
ERROR: Download of https://dl.bintray.com/lovell/sharp/... failed

### ISSUE THREAD

**Issue by smithb1994** [lovell/sharp#841]
It appears the link to the binary for sharp is having issues on npm install.
I'm getting this error:
`ERROR: Download of https://dl.bintray.com/lovell/sharp/libvips-8.5.5-linux-x64.tar.gz failed: Response code 500 (Internal Server Error)`  
  
It appears the link `https://dl.bintray.com/lovell/sharp/libvips-8.5.5-linux-x64.tar.gz` is having issues.

**Comment by smithb1994** [comment]
Never mind, the error must have been temporary with the website. It's working fine now.

**Comment by bmathews** [comment]
Happens pretty frequently lately. 😬

**Comment by lovell** [comment]
Please check http://status.bintray.com/ for any relevant announcements and direct feedback to https://twitter.com/bintray

**Comment by lovell** [comment]
http://status.bintray.com/incidents/lp493rrr4xqm

**Comment by lovell** [comment]
@jbaruch I've been getting a lot of negative feedback about Bintray availability recently. Are you able to help/comment?

http://status.bintray.com/incidents/lp493rrr4xqm claims an hour of "degraded download speeds" today but messages, comments and issues I've seen, when added a collapse in download stats, suggest this has been ongoing since around 07:30 UTC, with problems reaching a peak around 14:00 UTC today and lasting for about 5 hours.

I'm thinking of switching to Github Releases for binary distribution... are you able to tempt me not to?

**Comment by lovell** [comment]
Some more evidence:
https://twitter.com/kylemathews/status/875084767259242496
https://github.com/gatsbyjs/gatsby/pull/1188#issuecomment-309093119

**Comment by develar** [comment]
@lovell Please consider to use Github releases instead of unreliable Bintray. e.g. electron-builder migrated to Github and now users are happy (last month Bintray returns or 404, or 500 error).

**Comment by aberezkin** [comment]
It's better to do something with this issue asap. I can't push my project in production because of it and I think I'm not the only one.

**Comment by lovell** [comment]
With ~6k downloads/day, it looks like we're hitting Bintray's 1TB/month limit.

As a workaround for deployments, you can either (a) globally install libvips first, or (b) create a `node_modules/sharp/packaging` directory, place the relevant `libvips-*.tar.gz` file in it and run `npm rebuild` to use it instead of attempting a download.

**Comment by aberezkin** [comment]
I use Heroku for production and I believe there is no way to install libvips using any of these workarounds. Is there some another way?

**Comment by lovell** [comment]
@aberezkin https://github.com/alex88/heroku-buildpack-vips or one of its more recently updated forks may help.

**Comment by jms** [comment]
looks like Bintray is no reliable today. Github could be a good alternative   
```> sharp@0.17.2 install /Users/jenkins/tests/node_modules/sharp
> node-gyp rebuild

ERROR: Download of https://dl.bintray.com/lovell/sharp/libvips-8.4.2-darwin-x64.tar.gz failed: Response code 500 (Internal Server Error)```

**Comment by lovell** [comment]
Commit 502ae78 will allow the base URL for the Bintray-hosted binary dependencies to be changed via the `SHARP_DIST_BASE_URL` environment variable. This will be in v0.18.2 onwards.

For example:
```sh
SHARP_DIST_BASE_URL="https://hostname/path/" npm install sharp
```
...should attempt to download `https://hostname/path/libvips-8.5.5-linux-x64.tar.gz` on Linux instead of using Bintray,

**Comment by lovell** [comment]
Bintray are reporting more problems today - see http://status.bintray.com/incidents/v4ghm1s1xrp9 - in my experience these errors occur well before and after the reported time window. 😿

**Comment by lovell** [comment]
Created #851 for the move to Github Releases.

**Comment by lovell** [comment]
v0.18.2 now available with support for `SHARP_DIST_BASE_URL`. Let's use #851 to track support for Github Releases.
