### ISSUE TITLE
Unable to create tarball for libvips 8.5.6 and its dependencies using packaging scripts

### ISSUE THREAD

**Issue by manu4543** [lovell/sharp#875]
It ends with

make[3]: Leaving directory `/deps/tiff/libtiff'
make[2]: Leaving directory `/deps/tiff/libtiff'
Making install in tools
make[2]: Entering directory `/deps/tiff/tools'
make[2]: Leaving directory `/deps/tiff/tools'
make[2]: *** No rule to make target `bmp2tiff.o', needed by `bmp2tiff'.  Stop.
make[1]: *** [install-recursive] Error 1
make: *** [install-strip] Error 2
make[1]: Leaving directory `/deps/tiff'

Full output is attached.
[output.txt](https://github.com/lovell/sharp/files/1167875/output.txt)

The reason I am creating this is because [Bintray](https://dl.bintray.com/lovell/sharp/) don't have binaries for 8.5.6 yet.

**Comment by lovell** [comment]
Not sure, I'll be able to look at this more closely the next time the packaging scripts are updated. Best guess would be that this is a libtiff 4.0.7 vs 4.0.8 thing.

**Comment by lovell** [comment]
I've updated the approach to patching libtiff in the packaging scripts. It appears the "official" libtiff tarballs are no longer patchable due to differences between files under version-controlled and those released. The changes in commit 7423d50 (temporary, may be rebased and disappear) fixes this by using a libtiff mirror directly.

**Comment by lovell** [comment]
These scripts now live in https://github.com/lovell/sharp-libvips/ and include the changes required to get libtiff to compile.
