### ISSUE TITLE
Win10 Install - Error: Can't find Python executable "python"

### ISSUE THREAD

**Issue by JoeEarly** [lovell/sharp#876]
Pretty new to JS so go easy folks. 

I have been trying to get this install but node keep throwing me this error: Error: Can't find Python executable "python"

[npm-debug.txt](https://github.com/lovell/sharp/files/1168087/npm-debug.txt)
<img width="1519" alt="untitled" src="https://user-images.githubusercontent.com/5208459/28499496-52f34a1c-6faf-11e7-8914-3743bce9a4f9.png">

So here I arrive :) 

node v6.10.3
Win10 Build 1607

**Comment by lovell** [comment]
Hello, is Python installed? http://sharp.dimens.io/en/stable/install/#prerequisites

(If you're unsure, [windows-build-tools](https://www.npmjs.com/package/windows-build-tools) is your best bet to get started.)

**Comment by JoeEarly** [comment]
For the of Christ Joe. Read the docs dont just scan them 🔢

**Comment by jeffswitzer** [comment]
I had a similar issue on windows 10. My problem was that node-gyp needs python2 and my PYTHON env var was pointing to python3. 

It's just that the error msg was a bit misleading because it kept saying it couldn't find mypythonpath/python.exe when it was really there, just the wrong version. As soon as I changed PYTHON env to python27 everything went smoothly.
